package cn.com.bbut.iy.itemmaster.entity.sa0055;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class SA0055 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0055.cashier_level
     *
     * @mbg.generated
     */
    private String cashierLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0055.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0055.cashier_parameter
     *
     * @mbg.generated
     */
    private String cashierParameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0055.effective_sts
     *
     * @mbg.generated
     */
    private String effectiveSts;
}