package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class AuditType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_type.n_typeid
     *
     * @mbg.generated
     */
    private Integer nTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_type.c_type_name
     *
     * @mbg.generated
     */
    private String cTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_type.c_url
     *
     * @mbg.generated
     */
    private String cUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_type.n_distinguish_typeid
     *
     * @mbg.generated
     */
    private String nDistinguishTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_type.c_url2
     *
     * @mbg.generated
     */
    private String cUrl2;
}