package cn.com.bbut.iy.itemmaster.entity;

import java.util.ArrayList;
import java.util.List;

public class CM9030Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected boolean needFoundRows = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public CM9030Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public void setNeedFoundRows(boolean needFoundRows) {
        this.needFoundRows=needFoundRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public boolean getNeedFoundRows() {
        return needFoundRows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andDepCdIsNull() {
            addCriterion("department_cd is null");
            return (Criteria) this;
        }

        public Criteria andDepCdIsNotNull() {
            addCriterion("department_cd is not null");
            return (Criteria) this;
        }

        public Criteria andDepCdEqualTo(String value) {
            addCriterion("department_cd =", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdNotEqualTo(String value) {
            addCriterion("department_cd <>", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdGreaterThan(String value) {
            addCriterion("department_cd >", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdGreaterThanOrEqualTo(String value) {
            addCriterion("department_cd >=", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdLessThan(String value) {
            addCriterion("department_cd <", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdLessThanOrEqualTo(String value) {
            addCriterion("department_cd <=", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdLike(String value) {
            addCriterion("department_cd like", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdNotLike(String value) {
            addCriterion("department_cd not like", value, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdIn(List<String> values) {
            addCriterion("department_cd in", values, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdNotIn(List<String> values) {
            addCriterion("department_cd not in", values, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdBetween(String value1, String value2) {
            addCriterion("department_cd between", value1, value2, "depCd");
            return (Criteria) this;
        }

        public Criteria andDepCdNotBetween(String value1, String value2) {
            addCriterion("department_cd not between", value1, value2, "depCd");
            return (Criteria) this;
        }

        public Criteria andDutyIsNull() {
            addCriterion("duty is null");
            return (Criteria) this;
        }

        public Criteria andDutyIsNotNull() {
            addCriterion("duty is not null");
            return (Criteria) this;
        }

        public Criteria andDutyEqualTo(String value) {
            addCriterion("duty =", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotEqualTo(String value) {
            addCriterion("duty <>", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyGreaterThan(String value) {
            addCriterion("duty >", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyGreaterThanOrEqualTo(String value) {
            addCriterion("duty >=", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLessThan(String value) {
            addCriterion("duty <", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLessThanOrEqualTo(String value) {
            addCriterion("duty <=", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLike(String value) {
            addCriterion("duty like", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotLike(String value) {
            addCriterion("duty not like", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyIn(List<String> values) {
            addCriterion("duty in", values, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotIn(List<String> values) {
            addCriterion("duty not in", values, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyBetween(String value1, String value2) {
            addCriterion("duty between", value1, value2, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotBetween(String value1, String value2) {
            addCriterion("duty not between", value1, value2, "duty");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNull() {
            addCriterion("identity_card is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNotNull() {
            addCriterion("identity_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardEqualTo(String value) {
            addCriterion("identity_card =", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotEqualTo(String value) {
            addCriterion("identity_card <>", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThan(String value) {
            addCriterion("identity_card >", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThanOrEqualTo(String value) {
            addCriterion("identity_card >=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThan(String value) {
            addCriterion("identity_card <", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThanOrEqualTo(String value) {
            addCriterion("identity_card <=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLike(String value) {
            addCriterion("identity_card like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotLike(String value) {
            addCriterion("identity_card not like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIn(List<String> values) {
            addCriterion("identity_card in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotIn(List<String> values) {
            addCriterion("identity_card not in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardBetween(String value1, String value2) {
            addCriterion("identity_card between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotBetween(String value1, String value2) {
            addCriterion("identity_card not between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("nationality is null");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("nationality is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("nationality =", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("nationality <>", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("nationality >", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("nationality >=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("nationality <", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("nationality <=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("nationality like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("nationality not like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityIn(List<String> values) {
            addCriterion("nationality in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotIn(List<String> values) {
            addCriterion("nationality not in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("nationality between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("nationality not between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNull() {
            addCriterion("native_place is null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNotNull() {
            addCriterion("native_place is not null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceEqualTo(String value) {
            addCriterion("native_place =", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotEqualTo(String value) {
            addCriterion("native_place <>", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThan(String value) {
            addCriterion("native_place >", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("native_place >=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThan(String value) {
            addCriterion("native_place <", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("native_place <=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLike(String value) {
            addCriterion("native_place like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotLike(String value) {
            addCriterion("native_place not like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIn(List<String> values) {
            addCriterion("native_place in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotIn(List<String> values) {
            addCriterion("native_place not in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceBetween(String value1, String value2) {
            addCriterion("native_place between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotBetween(String value1, String value2) {
            addCriterion("native_place not between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("nation is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("nation is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("nation =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("nation <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("nation >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("nation >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("nation <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("nation <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("nation like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("nation not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("nation in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("nation not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("nation between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("nation not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andPostAddressIsNull() {
            addCriterion("post_address is null");
            return (Criteria) this;
        }

        public Criteria andPostAddressIsNotNull() {
            addCriterion("post_address is not null");
            return (Criteria) this;
        }

        public Criteria andPostAddressEqualTo(String value) {
            addCriterion("post_address =", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressNotEqualTo(String value) {
            addCriterion("post_address <>", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressGreaterThan(String value) {
            addCriterion("post_address >", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressGreaterThanOrEqualTo(String value) {
            addCriterion("post_address >=", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressLessThan(String value) {
            addCriterion("post_address <", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressLessThanOrEqualTo(String value) {
            addCriterion("post_address <=", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressLike(String value) {
            addCriterion("post_address like", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressNotLike(String value) {
            addCriterion("post_address not like", value, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressIn(List<String> values) {
            addCriterion("post_address in", values, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressNotIn(List<String> values) {
            addCriterion("post_address not in", values, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressBetween(String value1, String value2) {
            addCriterion("post_address between", value1, value2, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostAddressNotBetween(String value1, String value2) {
            addCriterion("post_address not between", value1, value2, "postAddress");
            return (Criteria) this;
        }

        public Criteria andPostZipCdIsNull() {
            addCriterion("post_zip_cd is null");
            return (Criteria) this;
        }

        public Criteria andPostZipCdIsNotNull() {
            addCriterion("post_zip_cd is not null");
            return (Criteria) this;
        }

        public Criteria andPostZipCdEqualTo(String value) {
            addCriterion("post_zip_cd =", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdNotEqualTo(String value) {
            addCriterion("post_zip_cd <>", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdGreaterThan(String value) {
            addCriterion("post_zip_cd >", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdGreaterThanOrEqualTo(String value) {
            addCriterion("post_zip_cd >=", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdLessThan(String value) {
            addCriterion("post_zip_cd <", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdLessThanOrEqualTo(String value) {
            addCriterion("post_zip_cd <=", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdLike(String value) {
            addCriterion("post_zip_cd like", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdNotLike(String value) {
            addCriterion("post_zip_cd not like", value, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdIn(List<String> values) {
            addCriterion("post_zip_cd in", values, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdNotIn(List<String> values) {
            addCriterion("post_zip_cd not in", values, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdBetween(String value1, String value2) {
            addCriterion("post_zip_cd between", value1, value2, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andPostZipCdNotBetween(String value1, String value2) {
            addCriterion("post_zip_cd not between", value1, value2, "postZipCd");
            return (Criteria) this;
        }

        public Criteria andEductionIsNull() {
            addCriterion("eduction is null");
            return (Criteria) this;
        }

        public Criteria andEductionIsNotNull() {
            addCriterion("eduction is not null");
            return (Criteria) this;
        }

        public Criteria andEductionEqualTo(String value) {
            addCriterion("eduction =", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionNotEqualTo(String value) {
            addCriterion("eduction <>", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionGreaterThan(String value) {
            addCriterion("eduction >", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionGreaterThanOrEqualTo(String value) {
            addCriterion("eduction >=", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionLessThan(String value) {
            addCriterion("eduction <", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionLessThanOrEqualTo(String value) {
            addCriterion("eduction <=", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionLike(String value) {
            addCriterion("eduction like", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionNotLike(String value) {
            addCriterion("eduction not like", value, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionIn(List<String> values) {
            addCriterion("eduction in", values, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionNotIn(List<String> values) {
            addCriterion("eduction not in", values, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionBetween(String value1, String value2) {
            addCriterion("eduction between", value1, value2, "eduction");
            return (Criteria) this;
        }

        public Criteria andEductionNotBetween(String value1, String value2) {
            addCriterion("eduction not between", value1, value2, "eduction");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(String value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(String value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(String value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(String value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(String value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLike(String value) {
            addCriterion("start_date like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotLike(String value) {
            addCriterion("start_date not like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<String> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<String> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(String value1, String value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(String value1, String value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("end_date like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("end_date not like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<String> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<String> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("mobile_no is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("mobile_no is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("mobile_no =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("mobile_no <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("mobile_no >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_no >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("mobile_no <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("mobile_no <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("mobile_no like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("mobile_no not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("mobile_no in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("mobile_no not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("mobile_no between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("mobile_no not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUpPasswordIsNull() {
            addCriterion("up_password is null");
            return (Criteria) this;
        }

        public Criteria andUpPasswordIsNotNull() {
            addCriterion("up_password is not null");
            return (Criteria) this;
        }

        public Criteria andUpPasswordEqualTo(String value) {
            addCriterion("up_password =", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordNotEqualTo(String value) {
            addCriterion("up_password <>", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordGreaterThan(String value) {
            addCriterion("up_password >", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("up_password >=", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordLessThan(String value) {
            addCriterion("up_password <", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordLessThanOrEqualTo(String value) {
            addCriterion("up_password <=", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordLike(String value) {
            addCriterion("up_password like", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordNotLike(String value) {
            addCriterion("up_password not like", value, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordIn(List<String> values) {
            addCriterion("up_password in", values, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordNotIn(List<String> values) {
            addCriterion("up_password not in", values, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordBetween(String value1, String value2) {
            addCriterion("up_password between", value1, value2, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpPasswordNotBetween(String value1, String value2) {
            addCriterion("up_password not between", value1, value2, "upPassword");
            return (Criteria) this;
        }

        public Criteria andUpAccountIsNull() {
            addCriterion("up_account is null");
            return (Criteria) this;
        }

        public Criteria andUpAccountIsNotNull() {
            addCriterion("up_account is not null");
            return (Criteria) this;
        }

        public Criteria andUpAccountEqualTo(String value) {
            addCriterion("up_account =", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountNotEqualTo(String value) {
            addCriterion("up_account <>", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountGreaterThan(String value) {
            addCriterion("up_account >", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountGreaterThanOrEqualTo(String value) {
            addCriterion("up_account >=", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountLessThan(String value) {
            addCriterion("up_account <", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountLessThanOrEqualTo(String value) {
            addCriterion("up_account <=", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountLike(String value) {
            addCriterion("up_account like", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountNotLike(String value) {
            addCriterion("up_account not like", value, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountIn(List<String> values) {
            addCriterion("up_account in", values, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountNotIn(List<String> values) {
            addCriterion("up_account not in", values, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountBetween(String value1, String value2) {
            addCriterion("up_account between", value1, value2, "upAccount");
            return (Criteria) this;
        }

        public Criteria andUpAccountNotBetween(String value1, String value2) {
            addCriterion("up_account not between", value1, value2, "upAccount");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateYmdIsNull() {
            addCriterion("create_ymd is null");
            return (Criteria) this;
        }

        public Criteria andCreateYmdIsNotNull() {
            addCriterion("create_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andCreateYmdEqualTo(String value) {
            addCriterion("create_ymd =", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotEqualTo(String value) {
            addCriterion("create_ymd <>", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdGreaterThan(String value) {
            addCriterion("create_ymd >", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdGreaterThanOrEqualTo(String value) {
            addCriterion("create_ymd >=", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdLessThan(String value) {
            addCriterion("create_ymd <", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdLessThanOrEqualTo(String value) {
            addCriterion("create_ymd <=", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdLike(String value) {
            addCriterion("create_ymd like", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotLike(String value) {
            addCriterion("create_ymd not like", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdIn(List<String> values) {
            addCriterion("create_ymd in", values, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotIn(List<String> values) {
            addCriterion("create_ymd not in", values, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdBetween(String value1, String value2) {
            addCriterion("create_ymd between", value1, value2, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotBetween(String value1, String value2) {
            addCriterion("create_ymd not between", value1, value2, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateHmsIsNull() {
            addCriterion("create_hms is null");
            return (Criteria) this;
        }

        public Criteria andCreateHmsIsNotNull() {
            addCriterion("create_hms is not null");
            return (Criteria) this;
        }

        public Criteria andCreateHmsEqualTo(String value) {
            addCriterion("create_hms =", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotEqualTo(String value) {
            addCriterion("create_hms <>", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsGreaterThan(String value) {
            addCriterion("create_hms >", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsGreaterThanOrEqualTo(String value) {
            addCriterion("create_hms >=", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsLessThan(String value) {
            addCriterion("create_hms <", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsLessThanOrEqualTo(String value) {
            addCriterion("create_hms <=", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsLike(String value) {
            addCriterion("create_hms like", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotLike(String value) {
            addCriterion("create_hms not like", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsIn(List<String> values) {
            addCriterion("create_hms in", values, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotIn(List<String> values) {
            addCriterion("create_hms not in", values, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsBetween(String value1, String value2) {
            addCriterion("create_hms between", value1, value2, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotBetween(String value1, String value2) {
            addCriterion("create_hms not between", value1, value2, "createHms");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdIsNull() {
            addCriterion("update_ymd is null");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdIsNotNull() {
            addCriterion("update_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdEqualTo(String value) {
            addCriterion("update_ymd =", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotEqualTo(String value) {
            addCriterion("update_ymd <>", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdGreaterThan(String value) {
            addCriterion("update_ymd >", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdGreaterThanOrEqualTo(String value) {
            addCriterion("update_ymd >=", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdLessThan(String value) {
            addCriterion("update_ymd <", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdLessThanOrEqualTo(String value) {
            addCriterion("update_ymd <=", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdLike(String value) {
            addCriterion("update_ymd like", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotLike(String value) {
            addCriterion("update_ymd not like", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdIn(List<String> values) {
            addCriterion("update_ymd in", values, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotIn(List<String> values) {
            addCriterion("update_ymd not in", values, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdBetween(String value1, String value2) {
            addCriterion("update_ymd between", value1, value2, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotBetween(String value1, String value2) {
            addCriterion("update_ymd not between", value1, value2, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsIsNull() {
            addCriterion("update_hms is null");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsIsNotNull() {
            addCriterion("update_hms is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsEqualTo(String value) {
            addCriterion("update_hms =", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotEqualTo(String value) {
            addCriterion("update_hms <>", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsGreaterThan(String value) {
            addCriterion("update_hms >", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsGreaterThanOrEqualTo(String value) {
            addCriterion("update_hms >=", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsLessThan(String value) {
            addCriterion("update_hms <", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsLessThanOrEqualTo(String value) {
            addCriterion("update_hms <=", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsLike(String value) {
            addCriterion("update_hms like", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotLike(String value) {
            addCriterion("update_hms not like", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsIn(List<String> values) {
            addCriterion("update_hms in", values, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotIn(List<String> values) {
            addCriterion("update_hms not in", values, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsBetween(String value1, String value2) {
            addCriterion("update_hms between", value1, value2, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotBetween(String value1, String value2) {
            addCriterion("update_hms not between", value1, value2, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdIsNull() {
            addCriterion("update_screen_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdIsNotNull() {
            addCriterion("update_screen_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdEqualTo(String value) {
            addCriterion("update_screen_id =", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotEqualTo(String value) {
            addCriterion("update_screen_id <>", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdGreaterThan(String value) {
            addCriterion("update_screen_id >", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_screen_id >=", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdLessThan(String value) {
            addCriterion("update_screen_id <", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdLessThanOrEqualTo(String value) {
            addCriterion("update_screen_id <=", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdLike(String value) {
            addCriterion("update_screen_id like", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotLike(String value) {
            addCriterion("update_screen_id not like", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdIn(List<String> values) {
            addCriterion("update_screen_id in", values, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotIn(List<String> values) {
            addCriterion("update_screen_id not in", values, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdBetween(String value1, String value2) {
            addCriterion("update_screen_id between", value1, value2, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotBetween(String value1, String value2) {
            addCriterion("update_screen_id not between", value1, value2, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressIsNull() {
            addCriterion("update_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressIsNotNull() {
            addCriterion("update_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressEqualTo(String value) {
            addCriterion("update_ip_address =", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotEqualTo(String value) {
            addCriterion("update_ip_address <>", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressGreaterThan(String value) {
            addCriterion("update_ip_address >", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("update_ip_address >=", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressLessThan(String value) {
            addCriterion("update_ip_address <", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressLessThanOrEqualTo(String value) {
            addCriterion("update_ip_address <=", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressLike(String value) {
            addCriterion("update_ip_address like", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotLike(String value) {
            addCriterion("update_ip_address not like", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressIn(List<String> values) {
            addCriterion("update_ip_address in", values, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotIn(List<String> values) {
            addCriterion("update_ip_address not in", values, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressBetween(String value1, String value2) {
            addCriterion("update_ip_address between", value1, value2, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotBetween(String value1, String value2) {
            addCriterion("update_ip_address not between", value1, value2, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgIsNull() {
            addCriterion("nr_update_flg is null");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgIsNotNull() {
            addCriterion("nr_update_flg is not null");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgEqualTo(String value) {
            addCriterion("nr_update_flg =", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotEqualTo(String value) {
            addCriterion("nr_update_flg <>", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgGreaterThan(String value) {
            addCriterion("nr_update_flg >", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgGreaterThanOrEqualTo(String value) {
            addCriterion("nr_update_flg >=", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgLessThan(String value) {
            addCriterion("nr_update_flg <", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgLessThanOrEqualTo(String value) {
            addCriterion("nr_update_flg <=", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgLike(String value) {
            addCriterion("nr_update_flg like", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotLike(String value) {
            addCriterion("nr_update_flg not like", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgIn(List<String> values) {
            addCriterion("nr_update_flg in", values, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotIn(List<String> values) {
            addCriterion("nr_update_flg not in", values, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgBetween(String value1, String value2) {
            addCriterion("nr_update_flg between", value1, value2, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotBetween(String value1, String value2) {
            addCriterion("nr_update_flg not between", value1, value2, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrYmdIsNull() {
            addCriterion("nr_ymd is null");
            return (Criteria) this;
        }

        public Criteria andNrYmdIsNotNull() {
            addCriterion("nr_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andNrYmdEqualTo(String value) {
            addCriterion("nr_ymd =", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotEqualTo(String value) {
            addCriterion("nr_ymd <>", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdGreaterThan(String value) {
            addCriterion("nr_ymd >", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdGreaterThanOrEqualTo(String value) {
            addCriterion("nr_ymd >=", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdLessThan(String value) {
            addCriterion("nr_ymd <", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdLessThanOrEqualTo(String value) {
            addCriterion("nr_ymd <=", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdLike(String value) {
            addCriterion("nr_ymd like", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotLike(String value) {
            addCriterion("nr_ymd not like", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdIn(List<String> values) {
            addCriterion("nr_ymd in", values, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotIn(List<String> values) {
            addCriterion("nr_ymd not in", values, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdBetween(String value1, String value2) {
            addCriterion("nr_ymd between", value1, value2, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotBetween(String value1, String value2) {
            addCriterion("nr_ymd not between", value1, value2, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrHmsIsNull() {
            addCriterion("nr_hms is null");
            return (Criteria) this;
        }

        public Criteria andNrHmsIsNotNull() {
            addCriterion("nr_hms is not null");
            return (Criteria) this;
        }

        public Criteria andNrHmsEqualTo(String value) {
            addCriterion("nr_hms =", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotEqualTo(String value) {
            addCriterion("nr_hms <>", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsGreaterThan(String value) {
            addCriterion("nr_hms >", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsGreaterThanOrEqualTo(String value) {
            addCriterion("nr_hms >=", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsLessThan(String value) {
            addCriterion("nr_hms <", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsLessThanOrEqualTo(String value) {
            addCriterion("nr_hms <=", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsLike(String value) {
            addCriterion("nr_hms like", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotLike(String value) {
            addCriterion("nr_hms not like", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsIn(List<String> values) {
            addCriterion("nr_hms in", values, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotIn(List<String> values) {
            addCriterion("nr_hms not in", values, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsBetween(String value1, String value2) {
            addCriterion("nr_hms between", value1, value2, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotBetween(String value1, String value2) {
            addCriterion("nr_hms not between", value1, value2, "nrHms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm9030
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm9030
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}