package cn.com.bbut.iy.itemmaster.entity;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IyBmItem extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.BM_TYPE
     *
     * @mbg.generated
     */
    private String bmType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.BM_CODE
     *
     * @mbg.generated
     */
    private String bmCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.STORE
     *
     * @mbg.generated
     */
    private String store;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.ITEM
     *
     * @mbg.generated
     */
    private String item;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.PRICE
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.PRICE_DISC
     *
     * @mbg.generated
     */
    private Integer priceDisc;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.DISC_RATE
     *
     * @mbg.generated
     */
    private BigDecimal discRate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.PRICE2ND
     *
     * @mbg.generated
     */
    private Integer price2nd;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.AB_FLG
     *
     * @mbg.generated
     */
    private String abFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.NUM_A
     *
     * @mbg.generated
     */
    private Integer numA;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM.NUM_B
     *
     * @mbg.generated
     */
    private Integer numB;
}