package cn.com.bbut.iy.itemmaster.entity;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IyBmItemCk extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.NEW_NO
     *
     * @mbg.generated
     */
    private String newNo;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.BM_TYPE
     *
     * @mbg.generated
     */
    private String bmType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.BM_CODE
     *
     * @mbg.generated
     */
    private String bmCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.STORE
     *
     * @mbg.generated
     */
    private String store;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.ITEM
     *
     * @mbg.generated
     */
    private String item;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.PRICE
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.PRICE_DISC
     *
     * @mbg.generated
     */
    private Integer priceDisc;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.DISC_RATE
     *
     * @mbg.generated
     */
    private BigDecimal discRate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.PRICE2ND
     *
     * @mbg.generated
     */
    private Integer price2nd;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.AB_FLG
     *
     * @mbg.generated
     */
    private String abFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.NUM_A
     *
     * @mbg.generated
     */
    private Integer numA;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.NUM_B
     *
     * @mbg.generated
     */
    private Integer numB;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_ITEM_CK.BM_ITEM_FLG
     *
     * @mbg.generated
     */
    private String bmItemFlg;
}