package cn.com.bbut.iy.itemmaster.entity;

import java.math.BigDecimal;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IyBmHis extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.COMPANY
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.NEW_NO
     *
     * @mbg.generated
     */
    private String newNo;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.NEW_NO_SUB
     *
     * @mbg.generated
     */
    private String newNoSub;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.STORE
     *
     * @mbg.generated
     */
    private String store;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.DPT
     *
     * @mbg.generated
     */
    private String dpt;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BUYER
     *
     * @mbg.generated
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_TYPE
     *
     * @mbg.generated
     */
    private String bmType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_CODE
     *
     * @mbg.generated
     */
    private String bmCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_NAME
     *
     * @mbg.generated
     */
    private String bmName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.ITEM_PRICE
     *
     * @mbg.generated
     */
    private Integer itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_NUMBER
     *
     * @mbg.generated
     */
    private Integer bmNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_PRICE
     *
     * @mbg.generated
     */
    private Integer bmPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_EFF_FROM
     *
     * @mbg.generated
     */
    private Integer bmEffFrom;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_EFF_TO
     *
     * @mbg.generated
     */
    private Integer bmEffTo;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_GROSS
     *
     * @mbg.generated
     */
    private Integer bmGross;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.NUM_A
     *
     * @mbg.generated
     */
    private Integer numA;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.NUM_B
     *
     * @mbg.generated
     */
    private Integer numB;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.DPT_FLG
     *
     * @mbg.generated
     */
    private String dptFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.RIGHT_FLG
     *
     * @mbg.generated
     */
    private String rightFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.CHECK_FLG
     *
     * @mbg.generated
     */
    private String checkFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.OP_FLG
     *
     * @mbg.generated
     */
    private String opFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.USERID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.REJECTREASON
     *
     * @mbg.generated
     */
    private String rejectreason;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.FIRST_FLG
     *
     * @mbg.generated
     */
    private String firstFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.BM_DISCOUNT_RATE
     *
     * @mbg.generated
     */
    private BigDecimal bmDiscountRate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.DPT_ALL
     *
     * @mbg.generated
     */
    private String dptAll;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.NEW_FLG
     *
     * @mbg.generated
     */
    private String newFlg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_BM_HIS.UPDATE_FLG
     *
     * @mbg.generated
     */
    private String updateFlg;
}