package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA0050 extends MA0050Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.additional_attribute_name
     *
     * @mbg.generated
     */
    private String additionalAttributeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.attribute_type
     *
     * @mbg.generated
     */
    private String attributeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.attribute_select_name
     *
     * @mbg.generated
     */
    private String attributeSelectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.effective_sts
     *
     * @mbg.generated
     */
    private String effectiveSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0050.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;
}