package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Ma1010aboutOd0000 {


    private String searchStr;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.store_name
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.structure_cd
     *
     * @mbg.generated
     */
    private String structureCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.system_start_date
     *
     * @mbg.generated
     */
    private String systemStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.system_end_date
     *
     * @mbg.generated
     */
    private String systemEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.test_order_start_date
     *
     * @mbg.generated
     */
    private String testOrderStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.test_order_end_date
     *
     * @mbg.generated
     */
    private String testOrderEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.order_start_date
     *
     * @mbg.generated
     */
    private String orderStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.order_end_date
     *
     * @mbg.generated
     */
    private String orderEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sale_start_date
     *
     * @mbg.generated
     */
    private String saleStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sale_end_date
     *
     * @mbg.generated
     */
    private String saleEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_db_server
     *
     * @mbg.generated
     */
    private String spDbServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_db
     *
     * @mbg.generated
     */
    private String spDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_sa_pwd
     *
     * @mbg.generated
     */
    private String spSaPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_ip_address
     *
     * @mbg.generated
     */
    private String spIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_port
     *
     * @mbg.generated
     */
    private String spPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_user_id
     *
     * @mbg.generated
     */
    private String spUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_password
     *
     * @mbg.generated
     */
    private String spPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_receive_path
     *
     * @mbg.generated
     */
    private String spReceivePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_send_path
     *
     * @mbg.generated
     */
    private String spSendPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_nr_flag
     *
     * @mbg.generated
     */
    private String spNrFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_article_allocate_flag
     *
     * @mbg.generated
     */
    private String sp_article_allocate_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_nr_step
     *
     * @mbg.generated
     */
    private Integer sp_nr_step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_file_send
     *
     * @mbg.generated
     */
    private String spFileSend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sp_store_status
     *
     * @mbg.generated
     */
    private String spStoreStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.od_file_time_diff
     *
     * @mbg.generated
     */
    private String odFileTimeDiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.nr_file_time_diff
     *
     * @mbg.generated
     */
    private String nrFileTimeDiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.nr_file_import_diff
     *
     * @mbg.generated
     */
    private String mrFileImportDiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.sale_upload_time_diff
     *
     * @mbg.generated
     */
    private String saleUploadTimeDiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1010.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;
}