package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA1040 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.license_cd
     *
     * @mbg.generated
     */
    private Integer licenseCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.pma_cd
     *
     * @mbg.generated
     */
    private String pmaCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.license_num
     *
     * @mbg.generated
     */
    private String licenseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.effective_start_date
     *
     * @mbg.generated
     */
    private String effectiveStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.effective_end_date
     *
     * @mbg.generated
     */
    private String effectiveEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.license_remark
     *
     * @mbg.generated
     */
    private String licenseRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.effective_sts
     *
     * @mbg.generated
     */
    private String effectiveSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.store_effective_start_date
     *
     * @mbg.generated
     */
    private String storeEffectiveStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1040.store_effective_end_date
     *
     * @mbg.generated
     */
    private String storeEffectiveEndDate;

    private String licenseType;
}