package cn.com.bbut.iy.itemmaster.entity;

import java.util.ArrayList;
import java.util.List;

public class MA1020Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected boolean needFoundRows = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public MA1020Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public void setNeedFoundRows(boolean needFoundRows) {
        this.needFoundRows=needFoundRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public boolean getNeedFoundRows() {
        return needFoundRows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStoreCdIsNull() {
            addCriterion("store_cd is null");
            return (Criteria) this;
        }

        public Criteria andStoreCdIsNotNull() {
            addCriterion("store_cd is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCdEqualTo(String value) {
            addCriterion("store_cd =", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotEqualTo(String value) {
            addCriterion("store_cd <>", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdGreaterThan(String value) {
            addCriterion("store_cd >", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdGreaterThanOrEqualTo(String value) {
            addCriterion("store_cd >=", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLessThan(String value) {
            addCriterion("store_cd <", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLessThanOrEqualTo(String value) {
            addCriterion("store_cd <=", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLike(String value) {
            addCriterion("store_cd like", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotLike(String value) {
            addCriterion("store_cd not like", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdIn(List<String> values) {
            addCriterion("store_cd in", values, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotIn(List<String> values) {
            addCriterion("store_cd not in", values, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdBetween(String value1, String value2) {
            addCriterion("store_cd between", value1, value2, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotBetween(String value1, String value2) {
            addCriterion("store_cd not between", value1, value2, "storeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdIsNull() {
            addCriterion("additional_attribute_cd is null");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdIsNotNull() {
            addCriterion("additional_attribute_cd is not null");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdEqualTo(String value) {
            addCriterion("additional_attribute_cd =", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdNotEqualTo(String value) {
            addCriterion("additional_attribute_cd <>", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdGreaterThan(String value) {
            addCriterion("additional_attribute_cd >", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdGreaterThanOrEqualTo(String value) {
            addCriterion("additional_attribute_cd >=", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdLessThan(String value) {
            addCriterion("additional_attribute_cd <", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdLessThanOrEqualTo(String value) {
            addCriterion("additional_attribute_cd <=", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdLike(String value) {
            addCriterion("additional_attribute_cd like", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdNotLike(String value) {
            addCriterion("additional_attribute_cd not like", value, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdIn(List<String> values) {
            addCriterion("additional_attribute_cd in", values, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdNotIn(List<String> values) {
            addCriterion("additional_attribute_cd not in", values, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdBetween(String value1, String value2) {
            addCriterion("additional_attribute_cd between", value1, value2, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttributeCdNotBetween(String value1, String value2) {
            addCriterion("additional_attribute_cd not between", value1, value2, "additionalAttributeCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdIsNull() {
            addCriterion("attribute_select_cd is null");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdIsNotNull() {
            addCriterion("attribute_select_cd is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdEqualTo(String value) {
            addCriterion("attribute_select_cd =", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdNotEqualTo(String value) {
            addCriterion("attribute_select_cd <>", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdGreaterThan(String value) {
            addCriterion("attribute_select_cd >", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdGreaterThanOrEqualTo(String value) {
            addCriterion("attribute_select_cd >=", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdLessThan(String value) {
            addCriterion("attribute_select_cd <", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdLessThanOrEqualTo(String value) {
            addCriterion("attribute_select_cd <=", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdLike(String value) {
            addCriterion("attribute_select_cd like", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdNotLike(String value) {
            addCriterion("attribute_select_cd not like", value, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdIn(List<String> values) {
            addCriterion("attribute_select_cd in", values, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdNotIn(List<String> values) {
            addCriterion("attribute_select_cd not in", values, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdBetween(String value1, String value2) {
            addCriterion("attribute_select_cd between", value1, value2, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andAttributeSelectCdNotBetween(String value1, String value2) {
            addCriterion("attribute_select_cd not between", value1, value2, "attributeSelectCd");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateIsNull() {
            addCriterion("effective_start_date is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateIsNotNull() {
            addCriterion("effective_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateEqualTo(String value) {
            addCriterion("effective_start_date =", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotEqualTo(String value) {
            addCriterion("effective_start_date <>", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateGreaterThan(String value) {
            addCriterion("effective_start_date >", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("effective_start_date >=", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateLessThan(String value) {
            addCriterion("effective_start_date <", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateLessThanOrEqualTo(String value) {
            addCriterion("effective_start_date <=", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateLike(String value) {
            addCriterion("effective_start_date like", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotLike(String value) {
            addCriterion("effective_start_date not like", value, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateIn(List<String> values) {
            addCriterion("effective_start_date in", values, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotIn(List<String> values) {
            addCriterion("effective_start_date not in", values, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateBetween(String value1, String value2) {
            addCriterion("effective_start_date between", value1, value2, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveStartDateNotBetween(String value1, String value2) {
            addCriterion("effective_start_date not between", value1, value2, "effectiveStartDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateIsNull() {
            addCriterion("effective_end_date is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateIsNotNull() {
            addCriterion("effective_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateEqualTo(String value) {
            addCriterion("effective_end_date =", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotEqualTo(String value) {
            addCriterion("effective_end_date <>", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateGreaterThan(String value) {
            addCriterion("effective_end_date >", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("effective_end_date >=", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateLessThan(String value) {
            addCriterion("effective_end_date <", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateLessThanOrEqualTo(String value) {
            addCriterion("effective_end_date <=", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateLike(String value) {
            addCriterion("effective_end_date like", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotLike(String value) {
            addCriterion("effective_end_date not like", value, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateIn(List<String> values) {
            addCriterion("effective_end_date in", values, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotIn(List<String> values) {
            addCriterion("effective_end_date not in", values, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateBetween(String value1, String value2) {
            addCriterion("effective_end_date between", value1, value2, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveEndDateNotBetween(String value1, String value2) {
            addCriterion("effective_end_date not between", value1, value2, "effectiveEndDate");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueIsNull() {
            addCriterion("additional_attribure_value is null");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueIsNotNull() {
            addCriterion("additional_attribure_value is not null");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueEqualTo(String value) {
            addCriterion("additional_attribure_value =", value, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueNotEqualTo(String value) {
            addCriterion("additional_attribure_value <>", value, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueGreaterThan(String value) {
            addCriterion("additional_attribure_value >", value, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueGreaterThanOrEqualTo(String value) {
            addCriterion("additional_attribure_value >=", value, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueLessThan(String value) {
            addCriterion("additional_attribure_value <", value, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueLessThanOrEqualTo(String value) {
            addCriterion("additional_attribure_value <=", value, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueIn(List<String> values) {
            addCriterion("additional_attribure_value in", values, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueNotIn(List<String> values) {
            addCriterion("additional_attribure_value not in", values, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueBetween(String value1, String value2) {
            addCriterion("additional_attribure_value between", value1, value2, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andAdditionalAttribureValueNotBetween(String value1, String value2) {
            addCriterion("additional_attribure_value not between", value1, value2, "additionalAttribureValue");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateYmdIsNull() {
            addCriterion("create_ymd is null");
            return (Criteria) this;
        }

        public Criteria andCreateYmdIsNotNull() {
            addCriterion("create_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andCreateYmdEqualTo(String value) {
            addCriterion("create_ymd =", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotEqualTo(String value) {
            addCriterion("create_ymd <>", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdGreaterThan(String value) {
            addCriterion("create_ymd >", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdGreaterThanOrEqualTo(String value) {
            addCriterion("create_ymd >=", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdLessThan(String value) {
            addCriterion("create_ymd <", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdLessThanOrEqualTo(String value) {
            addCriterion("create_ymd <=", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdLike(String value) {
            addCriterion("create_ymd like", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotLike(String value) {
            addCriterion("create_ymd not like", value, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdIn(List<String> values) {
            addCriterion("create_ymd in", values, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotIn(List<String> values) {
            addCriterion("create_ymd not in", values, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdBetween(String value1, String value2) {
            addCriterion("create_ymd between", value1, value2, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateYmdNotBetween(String value1, String value2) {
            addCriterion("create_ymd not between", value1, value2, "createYmd");
            return (Criteria) this;
        }

        public Criteria andCreateHmsIsNull() {
            addCriterion("create_hms is null");
            return (Criteria) this;
        }

        public Criteria andCreateHmsIsNotNull() {
            addCriterion("create_hms is not null");
            return (Criteria) this;
        }

        public Criteria andCreateHmsEqualTo(String value) {
            addCriterion("create_hms =", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotEqualTo(String value) {
            addCriterion("create_hms <>", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsGreaterThan(String value) {
            addCriterion("create_hms >", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsGreaterThanOrEqualTo(String value) {
            addCriterion("create_hms >=", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsLessThan(String value) {
            addCriterion("create_hms <", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsLessThanOrEqualTo(String value) {
            addCriterion("create_hms <=", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsLike(String value) {
            addCriterion("create_hms like", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotLike(String value) {
            addCriterion("create_hms not like", value, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsIn(List<String> values) {
            addCriterion("create_hms in", values, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotIn(List<String> values) {
            addCriterion("create_hms not in", values, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsBetween(String value1, String value2) {
            addCriterion("create_hms between", value1, value2, "createHms");
            return (Criteria) this;
        }

        public Criteria andCreateHmsNotBetween(String value1, String value2) {
            addCriterion("create_hms not between", value1, value2, "createHms");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdIsNull() {
            addCriterion("update_ymd is null");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdIsNotNull() {
            addCriterion("update_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdEqualTo(String value) {
            addCriterion("update_ymd =", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotEqualTo(String value) {
            addCriterion("update_ymd <>", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdGreaterThan(String value) {
            addCriterion("update_ymd >", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdGreaterThanOrEqualTo(String value) {
            addCriterion("update_ymd >=", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdLessThan(String value) {
            addCriterion("update_ymd <", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdLessThanOrEqualTo(String value) {
            addCriterion("update_ymd <=", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdLike(String value) {
            addCriterion("update_ymd like", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotLike(String value) {
            addCriterion("update_ymd not like", value, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdIn(List<String> values) {
            addCriterion("update_ymd in", values, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotIn(List<String> values) {
            addCriterion("update_ymd not in", values, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdBetween(String value1, String value2) {
            addCriterion("update_ymd between", value1, value2, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateYmdNotBetween(String value1, String value2) {
            addCriterion("update_ymd not between", value1, value2, "updateYmd");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsIsNull() {
            addCriterion("update_hms is null");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsIsNotNull() {
            addCriterion("update_hms is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsEqualTo(String value) {
            addCriterion("update_hms =", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotEqualTo(String value) {
            addCriterion("update_hms <>", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsGreaterThan(String value) {
            addCriterion("update_hms >", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsGreaterThanOrEqualTo(String value) {
            addCriterion("update_hms >=", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsLessThan(String value) {
            addCriterion("update_hms <", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsLessThanOrEqualTo(String value) {
            addCriterion("update_hms <=", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsLike(String value) {
            addCriterion("update_hms like", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotLike(String value) {
            addCriterion("update_hms not like", value, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsIn(List<String> values) {
            addCriterion("update_hms in", values, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotIn(List<String> values) {
            addCriterion("update_hms not in", values, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsBetween(String value1, String value2) {
            addCriterion("update_hms between", value1, value2, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateHmsNotBetween(String value1, String value2) {
            addCriterion("update_hms not between", value1, value2, "updateHms");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdIsNull() {
            addCriterion("update_screen_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdIsNotNull() {
            addCriterion("update_screen_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdEqualTo(String value) {
            addCriterion("update_screen_id =", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotEqualTo(String value) {
            addCriterion("update_screen_id <>", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdGreaterThan(String value) {
            addCriterion("update_screen_id >", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_screen_id >=", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdLessThan(String value) {
            addCriterion("update_screen_id <", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdLessThanOrEqualTo(String value) {
            addCriterion("update_screen_id <=", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdLike(String value) {
            addCriterion("update_screen_id like", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotLike(String value) {
            addCriterion("update_screen_id not like", value, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdIn(List<String> values) {
            addCriterion("update_screen_id in", values, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotIn(List<String> values) {
            addCriterion("update_screen_id not in", values, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdBetween(String value1, String value2) {
            addCriterion("update_screen_id between", value1, value2, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateScreenIdNotBetween(String value1, String value2) {
            addCriterion("update_screen_id not between", value1, value2, "updateScreenId");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressIsNull() {
            addCriterion("update_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressIsNotNull() {
            addCriterion("update_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressEqualTo(String value) {
            addCriterion("update_ip_address =", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotEqualTo(String value) {
            addCriterion("update_ip_address <>", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressGreaterThan(String value) {
            addCriterion("update_ip_address >", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("update_ip_address >=", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressLessThan(String value) {
            addCriterion("update_ip_address <", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressLessThanOrEqualTo(String value) {
            addCriterion("update_ip_address <=", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressLike(String value) {
            addCriterion("update_ip_address like", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotLike(String value) {
            addCriterion("update_ip_address not like", value, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressIn(List<String> values) {
            addCriterion("update_ip_address in", values, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotIn(List<String> values) {
            addCriterion("update_ip_address not in", values, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressBetween(String value1, String value2) {
            addCriterion("update_ip_address between", value1, value2, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andUpdateIpAddressNotBetween(String value1, String value2) {
            addCriterion("update_ip_address not between", value1, value2, "updateIpAddress");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgIsNull() {
            addCriterion("nr_update_flg is null");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgIsNotNull() {
            addCriterion("nr_update_flg is not null");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgEqualTo(String value) {
            addCriterion("nr_update_flg =", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotEqualTo(String value) {
            addCriterion("nr_update_flg <>", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgGreaterThan(String value) {
            addCriterion("nr_update_flg >", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgGreaterThanOrEqualTo(String value) {
            addCriterion("nr_update_flg >=", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgLessThan(String value) {
            addCriterion("nr_update_flg <", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgLessThanOrEqualTo(String value) {
            addCriterion("nr_update_flg <=", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgLike(String value) {
            addCriterion("nr_update_flg like", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotLike(String value) {
            addCriterion("nr_update_flg not like", value, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgIn(List<String> values) {
            addCriterion("nr_update_flg in", values, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotIn(List<String> values) {
            addCriterion("nr_update_flg not in", values, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgBetween(String value1, String value2) {
            addCriterion("nr_update_flg between", value1, value2, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrUpdateFlgNotBetween(String value1, String value2) {
            addCriterion("nr_update_flg not between", value1, value2, "nrUpdateFlg");
            return (Criteria) this;
        }

        public Criteria andNrYmdIsNull() {
            addCriterion("nr_ymd is null");
            return (Criteria) this;
        }

        public Criteria andNrYmdIsNotNull() {
            addCriterion("nr_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andNrYmdEqualTo(String value) {
            addCriterion("nr_ymd =", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotEqualTo(String value) {
            addCriterion("nr_ymd <>", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdGreaterThan(String value) {
            addCriterion("nr_ymd >", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdGreaterThanOrEqualTo(String value) {
            addCriterion("nr_ymd >=", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdLessThan(String value) {
            addCriterion("nr_ymd <", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdLessThanOrEqualTo(String value) {
            addCriterion("nr_ymd <=", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdLike(String value) {
            addCriterion("nr_ymd like", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotLike(String value) {
            addCriterion("nr_ymd not like", value, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdIn(List<String> values) {
            addCriterion("nr_ymd in", values, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotIn(List<String> values) {
            addCriterion("nr_ymd not in", values, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdBetween(String value1, String value2) {
            addCriterion("nr_ymd between", value1, value2, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrYmdNotBetween(String value1, String value2) {
            addCriterion("nr_ymd not between", value1, value2, "nrYmd");
            return (Criteria) this;
        }

        public Criteria andNrHmsIsNull() {
            addCriterion("nr_hms is null");
            return (Criteria) this;
        }

        public Criteria andNrHmsIsNotNull() {
            addCriterion("nr_hms is not null");
            return (Criteria) this;
        }

        public Criteria andNrHmsEqualTo(String value) {
            addCriterion("nr_hms =", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotEqualTo(String value) {
            addCriterion("nr_hms <>", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsGreaterThan(String value) {
            addCriterion("nr_hms >", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsGreaterThanOrEqualTo(String value) {
            addCriterion("nr_hms >=", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsLessThan(String value) {
            addCriterion("nr_hms <", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsLessThanOrEqualTo(String value) {
            addCriterion("nr_hms <=", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsLike(String value) {
            addCriterion("nr_hms like", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotLike(String value) {
            addCriterion("nr_hms not like", value, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsIn(List<String> values) {
            addCriterion("nr_hms in", values, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotIn(List<String> values) {
            addCriterion("nr_hms not in", values, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsBetween(String value1, String value2) {
            addCriterion("nr_hms between", value1, value2, "nrHms");
            return (Criteria) this;
        }

        public Criteria andNrHmsNotBetween(String value1, String value2) {
            addCriterion("nr_hms not between", value1, value2, "nrHms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ma1020
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ma1020
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}