package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA4340 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.launching_time
     *
     * @mbg.generated
     */
    private String launchingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.start_order_date
     *
     * @mbg.generated
     */
    private String startOrderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.vendor_id
     *
     * @mbg.generated
     */
    private String vendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.barcode
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.dep_cd
     *
     * @mbg.generated
     */
    private String depCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.selling_price
     *
     * @mbg.generated
     */
    private BigDecimal sellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.orgin
     *
     * @mbg.generated
     */
    private String orgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.shelf_life
     *
     * @mbg.generated
     */
    private String shelfLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.moq
     *
     * @mbg.generated
     */
    private String moq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.moa
     *
     * @mbg.generated
     */
    private String moa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.posm
     *
     * @mbg.generated
     */
    private String posm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_vendor_id
     *
     * @mbg.generated
     */
    private String descriptionVendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_item_code
     *
     * @mbg.generated
     */
    private String descriptionItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_barcode
     *
     * @mbg.generated
     */
    private String descriptionBarcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_product_name
     *
     * @mbg.generated
     */
    private String descriptionProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_order
     *
     * @mbg.generated
     */
    private String descriptionOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.order_method
     *
     * @mbg.generated
     */
    private String orderMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.order_schedule
     *
     * @mbg.generated
     */
    private String orderSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.display_position
     *
     * @mbg.generated
     */
    private String displayPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.bad_merchandise
     *
     * @mbg.generated
     */
    private String badMerchandise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.returnable
     *
     * @mbg.generated
     */
    private String returnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.exchange_goods
     *
     * @mbg.generated
     */
    private String exchangeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.sop
     *
     * @mbg.generated
     */
    private String sop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.selling_method
     *
     * @mbg.generated
     */
    private String sellingMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;
}