package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA8260 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.acc_date
     *
     * @mbg.generated
     */
    private String accDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.pollution_level
     *
     * @mbg.generated
     */
    private String pollutionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.create_ymd
     *
     * @mbg.generated
     */
    private String createYMD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.create_hms
     *
     * @mbg.generated
     */
    private String createHMS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.update_ymd
     *
     * @mbg.generated
     */
    private String updateYMD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.update_hms
     *
     * @mbg.generated
     */
    private String updateHMS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYMD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.nr_hms
     *
     * @mbg.generated
     */
    private String nrHMS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8260.structure_cd
     *
     * @mbg.generated
     */
    private String structureCd;
}