package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Mb0030Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb0030.file_cd
     *
     * @mbg.generated
     */
    private String fileCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb0030.excel_group_cd
     *
     * @mbg.generated
     */
    private String excelGroupCd;
}