package cn.com.bbut.iy.itemmaster.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
@Component
public class MB1000 extends MB1000Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.store_name
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.business_date
     *
     * @mbg.generated
     */
    private Date businessDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.trans_date
     *
     * @mbg.generated
     */
    private Date transDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.receipt_no
     *
     * @mbg.generated
     */
    private String receiptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.amount_ck
     *
     * @mbg.generated
     */
    private BigDecimal amountCk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.reference
     *
     * @mbg.generated
     */
    private String reference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.ref_date
     *
     * @mbg.generated
     */
    private Date refDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.create_date
     *
     * @mbg.generated
     */
    private String createDate;
}