package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MB1000Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.id
     *
     * @mbg.generated
     */
    private String Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1000.invoice_no
     *
     * @mbg.generated
     */
    private String invoiceNo;
}