package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
@Component
public class Mb1700 extends Mb1700Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1700.trans_amount
     *
     * @mbg.generated
     */
    private BigDecimal transAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1700.partner_username
     *
     * @mbg.generated
     */
    private String partnerUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1700.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1700.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1700.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    private BigDecimal ckQty;

    private BigDecimal ckAmount;

    private BigDecimal thirdQty;

    private BigDecimal thirdAmount;

    private BigDecimal varyQty;

    private BigDecimal varyAmount;
}