package cn.com.bbut.iy.itemmaster.entity;

import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Mb1800 extends Mb1800Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.trans_cd
     *
     * @mbg.generated
     */
    private String transCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.third_qty
     *
     * @mbg.generated
     */
    private BigDecimal thirdQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.third_amount
     *
     * @mbg.generated
     */
    private BigDecimal thirdAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.ck_qty
     *
     * @mbg.generated
     */
    private BigDecimal ckQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.ck_amount
     *
     * @mbg.generated
     */
    private BigDecimal ckAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.vary_qty
     *
     * @mbg.generated
     */
    private BigDecimal varyQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.vary_amount
     *
     * @mbg.generated
     */
    private BigDecimal varyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb1800.t_date
     *
     * @mbg.generated
     */
    private Date tDate;
}