package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MyMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.approval_type
     *
     * @mbggenerated
     */
    private String approvalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.approval_status
     *
     * @mbggenerated
     */
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.submitter_code
     *
     * @mbggenerated
     */
    private String submitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.approval_category
     *
     * @mbggenerated
     */
    private String approvalCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.submitter_name
     *
     * @mbggenerated
     */
    private String submitterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.submission_date
     *
     * @mbggenerated
     */
    private String submissionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_message.approval_records
     *
     * @mbggenerated
     */
    private String approvalRecords;
}