package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MySubmissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.approval_category
     *
     * @mbggenerated
     */
    private String approvalCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.approval_type
     *
     * @mbggenerated
     */
    private String approvalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.descriptions
     *
     * @mbggenerated
     */
    private String descriptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.record_id
     *
     * @mbggenerated
     */
    private Integer nRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.url
     *
     * @mbggenerated
     */
    private String URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.submitter_code
     *
     * @mbggenerated
     */
    private String submitterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.submitter_name
     *
     * @mbggenerated
     */
    private String submitterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.operatorname
     *
     * @mbggenerated
     */
    private String operatorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.approval_records
     *
     * @mbggenerated
     */
    private String approvalRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.approval_status
     *
     * @mbggenerated
     */
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_submissions.submissions_date
     *
     * @mbggenerated
     */
    private String submissionsDate;
}