package cn.com.bbut.iy.itemmaster.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MySubbmitter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.user_status
     *
     * @mbggenerated
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.telephone_no
     *
     * @mbggenerated
     */
    private String telephoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.mobilephone_no
     *
     * @mbggenerated
     */
    private String mobilephoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.address
     *
     * @mbggenerated
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_subbmitter.postal_code
     *
     * @mbggenerated
     */
    private String postalCode;
}