//package cn.com.bbut.iy.itemmaster.entity;
//
//import lombok.AllArgsConstructor;
//import lombok.Data;
//import lombok.EqualsAndHashCode;
//import lombok.NoArgsConstructor;
//
//@Data
//@EqualsAndHashCode(callSuper = false)
//@AllArgsConstructor
//@NoArgsConstructor
//public class OD0000DirectSupplierInq extends OD0000DirectSupplierInqKey {
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.org_order_id
//     *
//     * @mbg.generated
//     */
//    private String orgOrderId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.vendor_id
//     *
//     * @mbg.generated
//     */
//    private String vendorId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.delivery_type_cd
//     *
//     * @mbg.generated
//     */
//    private String deliveryTypeCd;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.delivery_center_id
//     *
//     * @mbg.generated
//     */
//    private String deliveryCenterId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.delivery_area_cd
//     *
//     * @mbg.generated
//     */
//    private String deliveryAreaCd;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.shipment
//     *
//     * @mbg.generated
//     */
//    private String shipment;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_type
//     *
//     * @mbg.generated
//     */
//    private String orderType;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_method
//     *
//     * @mbg.generated
//     */
//    private String orderMethod;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.payment_type
//     *
//     * @mbg.generated
//     */
//    private String paymentType;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.promotion_id
//     *
//     * @mbg.generated
//     */
//    private String promotionId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_date
//     *
//     * @mbg.generated
//     */
//    private String orderDate;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.delivery_date
//     *
//     * @mbg.generated
//     */
//    private String deliveryDate;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.expire_date
//     *
//     * @mbg.generated
//     */
//    private String expireDate;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.receive_date
//     *
//     * @mbg.generated
//     */
//    private String receiveDate;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.vendor_address
//     *
//     * @mbg.generated
//     */
//    private String vendorAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.store_address
//     *
//     * @mbg.generated
//     */
//    private String storeAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_sts
//     *
//     * @mbg.generated
//     */
//    private String orderSts;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.nr_flg
//     *
//     * @mbg.generated
//     */
//    private String nrFlg;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_remark
//     *
//     * @mbg.generated
//     */
//    private String orderRemark;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.purchase_vat_cd
//     *
//     * @mbg.generated
//     */
//    private String purchaseVatCd;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.tax_rate
//     *
//     * @mbg.generated
//     */
//    private BigDecimal taxRate;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_amt
//     *
//     * @mbg.generated
//     */
//    private BigDecimal orderAmt;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_tax
//     *
//     * @mbg.generated
//     */
//    private BigDecimal orderTax;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.receive_amt
//     *
//     * @mbg.generated
//     */
//    private BigDecimal receiveAmt;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.receive_tax
//     *
//     * @mbg.generated
//     */
//    private BigDecimal receiveTax;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.upload_flg
//     *
//     * @mbg.generated
//     */
//    private String uploadFlg;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.upload_date
//     *
//     * @mbg.generated
//     */
//    private String uploadDate;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.create_user_id
//     *
//     * @mbg.generated
//     */
//    private String createUserId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.create_ymd
//     *
//     * @mbg.generated
//     */
//    private String createYmd;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.create_hms
//     *
//     * @mbg.generated
//     */
//    private String createHms;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.update_user_id
//     *
//     * @mbg.generated
//     */
//    private String updateUserId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.update_ymd
//     *
//     * @mbg.generated
//     */
//    private String updateYmd;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.update_hms
//     *
//     * @mbg.generated
//     */
//    private String updateHms;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.update_screen_id
//     *
//     * @mbg.generated
//     */
//    private String updateScreenId;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.update_ip_address
//     *
//     * @mbg.generated
//     */
//    private String updateIpAddress;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.nr_update_flg
//     *
//     * @mbg.generated
//     */
//    private String nrUpdateFlg;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.nr_ymd
//     *
//     * @mbg.generated
//     */
//    private String nrYmd;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.nr_hms
//     *
//     * @mbg.generated
//     */
//    private String nrHms;
//
//    /**
//     *
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column od0000.order_differentiate
//     *
//     * @mbg.generated
//     */
//    private String orderDifferentiate;
//}