package cn.com.bbut.iy.itemmaster.entity.sa0050;

import java.util.ArrayList;
import java.util.List;

public class SA0050Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected boolean needFoundRows = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public SA0050Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public void setNeedFoundRows(boolean needFoundRows) {
        this.needFoundRows=needFoundRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public boolean getNeedFoundRows() {
        return needFoundRows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCashierIdIsNull() {
            addCriterion("cashier_id is null");
            return (Criteria) this;
        }

        public Criteria andCashierIdIsNotNull() {
            addCriterion("cashier_id is not null");
            return (Criteria) this;
        }

        public Criteria andCashierIdEqualTo(String value) {
            addCriterion("cashier_id =", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdNotEqualTo(String value) {
            addCriterion("cashier_id <>", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdGreaterThan(String value) {
            addCriterion("cashier_id >", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdGreaterThanOrEqualTo(String value) {
            addCriterion("cashier_id >=", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdLessThan(String value) {
            addCriterion("cashier_id <", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdLessThanOrEqualTo(String value) {
            addCriterion("cashier_id <=", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdLike(String value) {
            addCriterion("cashier_id like", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdNotLike(String value) {
            addCriterion("cashier_id not like", value, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdIn(List<String> values) {
            addCriterion("cashier_id in", values, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdNotIn(List<String> values) {
            addCriterion("cashier_id not in", values, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdBetween(String value1, String value2) {
            addCriterion("cashier_id between", value1, value2, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierIdNotBetween(String value1, String value2) {
            addCriterion("cashier_id not between", value1, value2, "cashierId");
            return (Criteria) this;
        }

        public Criteria andCashierNameIsNull() {
            addCriterion("cashier_name is null");
            return (Criteria) this;
        }

        public Criteria andCashierNameIsNotNull() {
            addCriterion("cashier_name is not null");
            return (Criteria) this;
        }

        public Criteria andCashierNameEqualTo(String value) {
            addCriterion("cashier_name =", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameNotEqualTo(String value) {
            addCriterion("cashier_name <>", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameGreaterThan(String value) {
            addCriterion("cashier_name >", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameGreaterThanOrEqualTo(String value) {
            addCriterion("cashier_name >=", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameLessThan(String value) {
            addCriterion("cashier_name <", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameLessThanOrEqualTo(String value) {
            addCriterion("cashier_name <=", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameLike(String value) {
            addCriterion("cashier_name like", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameNotLike(String value) {
            addCriterion("cashier_name not like", value, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameIn(List<String> values) {
            addCriterion("cashier_name in", values, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameNotIn(List<String> values) {
            addCriterion("cashier_name not in", values, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameBetween(String value1, String value2) {
            addCriterion("cashier_name between", value1, value2, "cashierName");
            return (Criteria) this;
        }

        public Criteria andCashierNameNotBetween(String value1, String value2) {
            addCriterion("cashier_name not between", value1, value2, "cashierName");
            return (Criteria) this;
        }

        public Criteria andDutyIsNull() {
            addCriterion("duty is null");
            return (Criteria) this;
        }

        public Criteria andDutyIsNotNull() {
            addCriterion("duty is not null");
            return (Criteria) this;
        }

        public Criteria andDutyEqualTo(String value) {
            addCriterion("duty =", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotEqualTo(String value) {
            addCriterion("duty <>", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyGreaterThan(String value) {
            addCriterion("duty >", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyGreaterThanOrEqualTo(String value) {
            addCriterion("duty >=", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLessThan(String value) {
            addCriterion("duty <", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLessThanOrEqualTo(String value) {
            addCriterion("duty <=", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLike(String value) {
            addCriterion("duty like", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotLike(String value) {
            addCriterion("duty not like", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyIn(List<String> values) {
            addCriterion("duty in", values, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotIn(List<String> values) {
            addCriterion("duty not in", values, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyBetween(String value1, String value2) {
            addCriterion("duty between", value1, value2, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotBetween(String value1, String value2) {
            addCriterion("duty not between", value1, value2, "duty");
            return (Criteria) this;
        }

        public Criteria andCashierLevelIsNull() {
            addCriterion("cashier_level is null");
            return (Criteria) this;
        }

        public Criteria andCashierLevelIsNotNull() {
            addCriterion("cashier_level is not null");
            return (Criteria) this;
        }

        public Criteria andCashierLevelEqualTo(String value) {
            addCriterion("cashier_level =", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelNotEqualTo(String value) {
            addCriterion("cashier_level <>", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelGreaterThan(String value) {
            addCriterion("cashier_level >", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelGreaterThanOrEqualTo(String value) {
            addCriterion("cashier_level >=", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelLessThan(String value) {
            addCriterion("cashier_level <", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelLessThanOrEqualTo(String value) {
            addCriterion("cashier_level <=", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelLike(String value) {
            addCriterion("cashier_level like", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelNotLike(String value) {
            addCriterion("cashier_level not like", value, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelIn(List<String> values) {
            addCriterion("cashier_level in", values, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelNotIn(List<String> values) {
            addCriterion("cashier_level not in", values, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelBetween(String value1, String value2) {
            addCriterion("cashier_level between", value1, value2, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierLevelNotBetween(String value1, String value2) {
            addCriterion("cashier_level not between", value1, value2, "cashierLevel");
            return (Criteria) this;
        }

        public Criteria andCashierParameterIsNull() {
            addCriterion("cashier_parameter is null");
            return (Criteria) this;
        }

        public Criteria andCashierParameterIsNotNull() {
            addCriterion("cashier_parameter is not null");
            return (Criteria) this;
        }

        public Criteria andCashierParameterEqualTo(String value) {
            addCriterion("cashier_parameter =", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterNotEqualTo(String value) {
            addCriterion("cashier_parameter <>", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterGreaterThan(String value) {
            addCriterion("cashier_parameter >", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterGreaterThanOrEqualTo(String value) {
            addCriterion("cashier_parameter >=", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterLessThan(String value) {
            addCriterion("cashier_parameter <", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterLessThanOrEqualTo(String value) {
            addCriterion("cashier_parameter <=", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterLike(String value) {
            addCriterion("cashier_parameter like", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterNotLike(String value) {
            addCriterion("cashier_parameter not like", value, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterIn(List<String> values) {
            addCriterion("cashier_parameter in", values, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterNotIn(List<String> values) {
            addCriterion("cashier_parameter not in", values, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterBetween(String value1, String value2) {
            addCriterion("cashier_parameter between", value1, value2, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierParameterNotBetween(String value1, String value2) {
            addCriterion("cashier_parameter not between", value1, value2, "cashierParameter");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordIsNull() {
            addCriterion("cashier_password is null");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordIsNotNull() {
            addCriterion("cashier_password is not null");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordEqualTo(String value) {
            addCriterion("cashier_password =", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordNotEqualTo(String value) {
            addCriterion("cashier_password <>", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordGreaterThan(String value) {
            addCriterion("cashier_password >", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("cashier_password >=", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordLessThan(String value) {
            addCriterion("cashier_password <", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordLessThanOrEqualTo(String value) {
            addCriterion("cashier_password <=", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordLike(String value) {
            addCriterion("cashier_password like", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordNotLike(String value) {
            addCriterion("cashier_password not like", value, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordIn(List<String> values) {
            addCriterion("cashier_password in", values, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordNotIn(List<String> values) {
            addCriterion("cashier_password not in", values, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordBetween(String value1, String value2) {
            addCriterion("cashier_password between", value1, value2, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andCashierPasswordNotBetween(String value1, String value2) {
            addCriterion("cashier_password not between", value1, value2, "cashierPassword");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsIsNull() {
            addCriterion("effective_sts is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsIsNotNull() {
            addCriterion("effective_sts is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsEqualTo(String value) {
            addCriterion("effective_sts =", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotEqualTo(String value) {
            addCriterion("effective_sts <>", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsGreaterThan(String value) {
            addCriterion("effective_sts >", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsGreaterThanOrEqualTo(String value) {
            addCriterion("effective_sts >=", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsLessThan(String value) {
            addCriterion("effective_sts <", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsLessThanOrEqualTo(String value) {
            addCriterion("effective_sts <=", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsLike(String value) {
            addCriterion("effective_sts like", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotLike(String value) {
            addCriterion("effective_sts not like", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsIn(List<String> values) {
            addCriterion("effective_sts in", values, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotIn(List<String> values) {
            addCriterion("effective_sts not in", values, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsBetween(String value1, String value2) {
            addCriterion("effective_sts between", value1, value2, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotBetween(String value1, String value2) {
            addCriterion("effective_sts not between", value1, value2, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andStoreCdIsNull() {
            addCriterion("store_cd is null");
            return (Criteria) this;
        }

        public Criteria andStoreCdIsNotNull() {
            addCriterion("store_cd is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCdEqualTo(String value) {
            addCriterion("store_cd =", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotEqualTo(String value) {
            addCriterion("store_cd <>", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdGreaterThan(String value) {
            addCriterion("store_cd >", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdGreaterThanOrEqualTo(String value) {
            addCriterion("store_cd >=", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLessThan(String value) {
            addCriterion("store_cd <", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLessThanOrEqualTo(String value) {
            addCriterion("store_cd <=", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdLike(String value) {
            addCriterion("store_cd like", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotLike(String value) {
            addCriterion("store_cd not like", value, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdIn(List<String> values) {
            addCriterion("store_cd in", values, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotIn(List<String> values) {
            addCriterion("store_cd not in", values, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdBetween(String value1, String value2) {
            addCriterion("store_cd between", value1, value2, "storeCd");
            return (Criteria) this;
        }

        public Criteria andStoreCdNotBetween(String value1, String value2) {
            addCriterion("store_cd not between", value1, value2, "storeCd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sa0050
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sa0050
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}