package cn.com.bbut.iy.itemmaster.entity.sa0050;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class SA0050 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.cashier_id
     *
     * @mbg.generated
     */
    private String cashierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.cashier_name
     *
     * @mbg.generated
     */
    private String cashierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.cashier_level
     *
     * @mbg.generated
     */
    private String cashierLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.cashier_parameter
     *
     * @mbg.generated
     */
    private String cashierParameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.cashier_password
     *
     * @mbg.generated
     */
    private String cashierPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.effective_sts
     *
     * @mbg.generated
     */
    private String effectiveSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0050.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;



    private String cashierEmail;

}