package cn.com.bbut.iy.itemmaster.entity.base;

import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Cm9060 extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_id
     *
     * @mbg.generated
     */
    private String spId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_name
     *
     * @mbg.generated
     */
    private String spName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_description
     *
     * @mbg.generated
     */
    private String spDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_value
     *
     * @mbg.generated
     */
    private String spValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_rsv_status
     *
     * @mbg.generated
     */
    private String spRsvStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_create_user_id
     *
     * @mbg.generated
     */
    private String sp_create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_create_date
     *
     * @mbg.generated
     */
    private String sp_create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_update_user_id
     *
     * @mbg.generated
     */
    private String sp_update_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.sp_update_date
     *
     * @mbg.generated
     */
    private String sp_update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.nr_update_flg
     *
     * @mbg.generated
     */
    private String nr_update_flg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.nr_ymd
     *
     * @mbg.generated
     */
    private String nr_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9060.nr_hms
     *
     * @mbg.generated
     */
    private String nr_hms;
}