package cn.com.bbut.iy.itemmaster.entity.base;

import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IyDpt extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.COMPANY
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.GRAND_DIV
     *
     * @mbg.generated
     */
    private String grandDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DEPARTMENT
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DPT
     *
     * @mbg.generated
     */
    private String dpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DPT_NAME_E
     *
     * @mbg.generated
     */
    private String dptNamee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DPT_NAME
     *
     * @mbg.generated
     */
    private String dptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DPT_NAME_SRT_E
     *
     * @mbg.generated
     */
    private String dptNameSrte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DPT_NAME_SRT
     *
     * @mbg.generated
     */
    private String dptNameSrt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.SEQ_NO
     *
     * @mbg.generated
     */
    private String seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.SALES_EXL_FLG
     *
     * @mbg.generated
     */
    private String salesExlFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.SUBT_EXL_FLG
     *
     * @mbg.generated
     */
    private String subtExlFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DISC_EXL_FLG
     *
     * @mbg.generated
     */
    private String discExlFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.ORDER_TYPE
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.C_P_KBN
     *
     * @mbg.generated
     */
    private String cpkbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DECREASE_RATE
     *
     * @mbg.generated
     */
    private Integer decreaseRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.TRN_COST_RATE
     *
     * @mbg.generated
     */
    private Integer trnCostRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.TENANT_KBN
     *
     * @mbg.generated
     */
    private String tenantKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.TENANT
     *
     * @mbg.generated
     */
    private String tenant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.LINE
     *
     * @mbg.generated
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.INV_TYPE
     *
     * @mbg.generated
     */
    private String invType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.INV_CYCLE
     *
     * @mbg.generated
     */
    private String invCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.TAX_FLG
     *
     * @mbg.generated
     */
    private String taxFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.TAX_RATE
     *
     * @mbg.generated
     */
    private Integer taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.PRICE_RATE
     *
     * @mbg.generated
     */
    private Integer priceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.STR_USE_FLG
     *
     * @mbg.generated
     */
    private String strUseFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.DPT_CODE_TYPE
     *
     * @mbg.generated
     */
    private String dptCodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.VAL_DATE
     *
     * @mbg.generated
     */
    private Integer valDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.TRAN_DATE
     *
     * @mbg.generated
     */
    private Integer tranDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.GEN_DATE
     *
     * @mbg.generated
     */
    private Integer genDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_DPT.ONLINE_DATE
     *
     * @mbg.generated
     */
    private Integer onlineDate;
}