package cn.com.bbut.iy.itemmaster.entity.base;

import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IyItemM extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.COMPANY
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_SYSTEM
     *
     * @mbg.generated
     */
    private String itemSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_NAME
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_NAME_E
     *
     * @mbg.generated
     */
    private String itemNameE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.RECIEPT_NAME
     *
     * @mbg.generated
     */
    private String recieptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ENTRY_BUYER
     *
     * @mbg.generated
     */
    private String entryBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM1
     *
     * @mbg.generated
     */
    private String item1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM1_ENTRY_DATE
     *
     * @mbg.generated
     */
    private Integer item1EntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM2
     *
     * @mbg.generated
     */
    private String item2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM2_ENTRY_DATE
     *
     * @mbg.generated
     */
    private Integer item2EntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM3
     *
     * @mbg.generated
     */
    private String item3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM3_ENTRY_DATE
     *
     * @mbg.generated
     */
    private Integer item3EntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM4
     *
     * @mbg.generated
     */
    private String item4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM4_ENTRY_DATE
     *
     * @mbg.generated
     */
    private Integer item4EntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM5
     *
     * @mbg.generated
     */
    private String item5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM5_ENTRY_DATE
     *
     * @mbg.generated
     */
    private Integer item5EntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_ORDER
     *
     * @mbg.generated
     */
    private String itemOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.DPT
     *
     * @mbg.generated
     */
    private String dpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.LINE
     *
     * @mbg.generated
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.CLASS
     *
     * @mbg.generated
     */
    private String clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.HINBAN
     *
     * @mbg.generated
     */
    private String hinban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.COLOR
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.SIZE1
     *
     * @mbg.generated
     */
    private String size1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.SUB_CLASS1
     *
     * @mbg.generated
     */
    private String subClass1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.SUB_CLASS2
     *
     * @mbg.generated
     */
    private String subClass2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.AREA
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.DELIVERY_LIMIT
     *
     * @mbg.generated
     */
    private String deliveryLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.SALES_LIMIT
     *
     * @mbg.generated
     */
    private String salesLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.TASTE_LIMIT
     *
     * @mbg.generated
     */
    private String tasteLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.MAKER
     *
     * @mbg.generated
     */
    private String maker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_MAKER
     *
     * @mbg.generated
     */
    private String itemMaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.CONTRACT_AMOUNT
     *
     * @mbg.generated
     */
    private String contractAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.CONTRACT_DATE_FROM
     *
     * @mbg.generated
     */
    private Integer contractDateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.CONTRACT_DATE_TO
     *
     * @mbg.generated
     */
    private Integer contractDateTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.COST
     *
     * @mbg.generated
     */
    private Integer cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.PRICE
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.TAX_RATE
     *
     * @mbg.generated
     */
    private Integer taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ORDER_TYPE
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.TAG_TYPE
     *
     * @mbg.generated
     */
    private String tagType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.DELIVERY_TYPE
     *
     * @mbg.generated
     */
    private String deliveryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.BUYING_TYPE
     *
     * @mbg.generated
     */
    private String buyingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.PCARD_TYPE
     *
     * @mbg.generated
     */
    private String pcardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.CONTRACT_NO1
     *
     * @mbg.generated
     */
    private String contractNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.CONTRACT_NO2
     *
     * @mbg.generated
     */
    private String contractNo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.VENDOR
     *
     * @mbg.generated
     */
    private String vendor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ONLINE_DATE
     *
     * @mbg.generated
     */
    private Integer onlineDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.BUY_TAX_RATE
     *
     * @mbg.generated
     */
    private Integer buyTaxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.TAX_TYPE
     *
     * @mbg.generated
     */
    private String taxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_ATTRIBUTE
     *
     * @mbg.generated
     */
    private String itemAttribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.BRAND
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.DESIGN
     *
     * @mbg.generated
     */
    private String design;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.FABRIC
     *
     * @mbg.generated
     */
    private String fabric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.PATTERN
     *
     * @mbg.generated
     */
    private String pattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.STYLE
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.LEAST_STOCK_AMOUNT
     *
     * @mbg.generated
     */
    private Integer leastStockAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.SURFACE_NUM
     *
     * @mbg.generated
     */
    private Integer surfaceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.DLMIN_NUM
     *
     * @mbg.generated
     */
    private Integer dlminNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_NAME_EL
     *
     * @mbg.generated
     */
    private String itemNameEl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.TEMPERATURE
     *
     * @mbg.generated
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_ITEM_M.ITEM_SEASON
     *
     * @mbg.generated
     */
    private String itemSeason;
}