package cn.com.bbut.iy.itemmaster.entity.base;

import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IymActorAssignmentRecord extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.ACTOR_ASS_ID
     *
     * @mbg.generated
     */
    private Integer actorAssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.OLD_USER_ID
     *
     * @mbg.generated
     */
    private String oldUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.NEW_USER_ID
     *
     * @mbg.generated
     */
    private String newUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.ROLE_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.OPERATION_FLG
     *
     * @mbg.generated
     */
    private Integer operationFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.UPDATE_USERID
     *
     * @mbg.generated
     */
    private String updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.START_TIME
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_M_ACTOR_ASSIGNMENT_RECORD.END_TIME
     *
     * @mbg.generated
     */
    private Date endTime;
}