package cn.com.bbut.iy.itemmaster.entity.base;

import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IymActorAssignmentInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.ACTOR_ASS_ID
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.FLG
     *
     * @mbg.generated
     */
    private Integer flg;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.START_DATE
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.END_DATE
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.UPDATE_USERID
     *
     * @mbg.generated
     */
    private String updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.ASS_USER_ID
     *
     * @mbg.generated
     */
    private String assUserId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_ACTOR_ASSIGNMENT_INFO.STATUS
     *
     * @mbg.generated
     */
    private Integer status;
}