package cn.com.bbut.iy.itemmaster.entity.base;

import java.util.Date;

import cn.shiy.common.pmgr.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IymRoleRemark extends BaseEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column IY_M_ROLE_REMARK.ROLE_ID
	 *
	 * @mbg.generated
	 */
	private Integer roleId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column IY_M_ROLE_REMARK.REMARK
	 *
	 * @mbg.generated
	 */
	private String remark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column IY_M_ROLE_REMARK.UPDATE_TIME
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column IY_M_ROLE_REMARK.UPDATE_USERID
	 *
	 * @mbg.generated
	 */
	private String updateUserid;
}