package cn.com.bbut.iy.itemmaster.entity.base;

import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class IyStore extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.COMPANY
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE
     *
     * @mbg.generated
     */
    private String store;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.ZONE
     *
     * @mbg.generated
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_NAME
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_OPEN_DATE
     *
     * @mbg.generated
     */
    private Integer storeOpenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_CLOSE_DATE
     *
     * @mbg.generated
     */
    private Integer storeCloseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_SALES_FLAG
     *
     * @mbg.generated
     */
    private String storeSalesFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_ORGANAIZE
     *
     * @mbg.generated
     */
    private String storeOrganaize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_SYSTEM_FROM
     *
     * @mbg.generated
     */
    private Integer storeSystemFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_SYSTEM_TO
     *
     * @mbg.generated
     */
    private Integer storeSystemTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.STORE_EXIST_KBN
     *
     * @mbg.generated
     */
    private String storeExistKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IY_STORE.ONLINE_DATE
     *
     * @mbg.generated
     */
    private Integer onlineDate;
}