package cn.com.bbut.iy.itemmaster.entity.base;

import java.util.ArrayList;
import java.util.List;

public class IyStoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected boolean needFoundRows = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public IyStoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public void setNeedFoundRows(boolean needFoundRows) {
        this.needFoundRows=needFoundRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public boolean getNeedFoundRows() {
        return needFoundRows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIsNull() {
            addCriterion("COMPANY is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("COMPANY is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("COMPANY =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("COMPANY <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("COMPANY >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("COMPANY <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("COMPANY <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("COMPANY like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("COMPANY not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("COMPANY in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("COMPANY not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("COMPANY between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("COMPANY not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andStoreIsNull() {
            addCriterion("STORE is null");
            return (Criteria) this;
        }

        public Criteria andStoreIsNotNull() {
            addCriterion("STORE is not null");
            return (Criteria) this;
        }

        public Criteria andStoreEqualTo(String value) {
            addCriterion("STORE =", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreNotEqualTo(String value) {
            addCriterion("STORE <>", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreGreaterThan(String value) {
            addCriterion("STORE >", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreGreaterThanOrEqualTo(String value) {
            addCriterion("STORE >=", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreLessThan(String value) {
            addCriterion("STORE <", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreLessThanOrEqualTo(String value) {
            addCriterion("STORE <=", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreLike(String value) {
            addCriterion("STORE like", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreNotLike(String value) {
            addCriterion("STORE not like", value, "store");
            return (Criteria) this;
        }

        public Criteria andStoreIn(List<String> values) {
            addCriterion("STORE in", values, "store");
            return (Criteria) this;
        }

        public Criteria andStoreNotIn(List<String> values) {
            addCriterion("STORE not in", values, "store");
            return (Criteria) this;
        }

        public Criteria andStoreBetween(String value1, String value2) {
            addCriterion("STORE between", value1, value2, "store");
            return (Criteria) this;
        }

        public Criteria andStoreNotBetween(String value1, String value2) {
            addCriterion("STORE not between", value1, value2, "store");
            return (Criteria) this;
        }

        public Criteria andZoneIsNull() {
            addCriterion("ZONE is null");
            return (Criteria) this;
        }

        public Criteria andZoneIsNotNull() {
            addCriterion("ZONE is not null");
            return (Criteria) this;
        }

        public Criteria andZoneEqualTo(String value) {
            addCriterion("ZONE =", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotEqualTo(String value) {
            addCriterion("ZONE <>", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThan(String value) {
            addCriterion("ZONE >", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThanOrEqualTo(String value) {
            addCriterion("ZONE >=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThan(String value) {
            addCriterion("ZONE <", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThanOrEqualTo(String value) {
            addCriterion("ZONE <=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLike(String value) {
            addCriterion("ZONE like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotLike(String value) {
            addCriterion("ZONE not like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneIn(List<String> values) {
            addCriterion("ZONE in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotIn(List<String> values) {
            addCriterion("ZONE not in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneBetween(String value1, String value2) {
            addCriterion("ZONE between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotBetween(String value1, String value2) {
            addCriterion("ZONE not between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNull() {
            addCriterion("STORE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNotNull() {
            addCriterion("STORE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNameEqualTo(String value) {
            addCriterion("STORE_NAME =", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotEqualTo(String value) {
            addCriterion("STORE_NAME <>", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThan(String value) {
            addCriterion("STORE_NAME >", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_NAME >=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThan(String value) {
            addCriterion("STORE_NAME <", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThanOrEqualTo(String value) {
            addCriterion("STORE_NAME <=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLike(String value) {
            addCriterion("STORE_NAME like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotLike(String value) {
            addCriterion("STORE_NAME not like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameIn(List<String> values) {
            addCriterion("STORE_NAME in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotIn(List<String> values) {
            addCriterion("STORE_NAME not in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameBetween(String value1, String value2) {
            addCriterion("STORE_NAME between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotBetween(String value1, String value2) {
            addCriterion("STORE_NAME not between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateIsNull() {
            addCriterion("STORE_OPEN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateIsNotNull() {
            addCriterion("STORE_OPEN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateEqualTo(Integer value) {
            addCriterion("STORE_OPEN_DATE =", value, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateNotEqualTo(Integer value) {
            addCriterion("STORE_OPEN_DATE <>", value, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateGreaterThan(Integer value) {
            addCriterion("STORE_OPEN_DATE >", value, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("STORE_OPEN_DATE >=", value, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateLessThan(Integer value) {
            addCriterion("STORE_OPEN_DATE <", value, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateLessThanOrEqualTo(Integer value) {
            addCriterion("STORE_OPEN_DATE <=", value, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateIn(List<Integer> values) {
            addCriterion("STORE_OPEN_DATE in", values, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateNotIn(List<Integer> values) {
            addCriterion("STORE_OPEN_DATE not in", values, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateBetween(Integer value1, Integer value2) {
            addCriterion("STORE_OPEN_DATE between", value1, value2, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreOpenDateNotBetween(Integer value1, Integer value2) {
            addCriterion("STORE_OPEN_DATE not between", value1, value2, "storeOpenDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateIsNull() {
            addCriterion("STORE_CLOSE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateIsNotNull() {
            addCriterion("STORE_CLOSE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateEqualTo(Integer value) {
            addCriterion("STORE_CLOSE_DATE =", value, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateNotEqualTo(Integer value) {
            addCriterion("STORE_CLOSE_DATE <>", value, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateGreaterThan(Integer value) {
            addCriterion("STORE_CLOSE_DATE >", value, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("STORE_CLOSE_DATE >=", value, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateLessThan(Integer value) {
            addCriterion("STORE_CLOSE_DATE <", value, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateLessThanOrEqualTo(Integer value) {
            addCriterion("STORE_CLOSE_DATE <=", value, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateIn(List<Integer> values) {
            addCriterion("STORE_CLOSE_DATE in", values, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateNotIn(List<Integer> values) {
            addCriterion("STORE_CLOSE_DATE not in", values, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateBetween(Integer value1, Integer value2) {
            addCriterion("STORE_CLOSE_DATE between", value1, value2, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreCloseDateNotBetween(Integer value1, Integer value2) {
            addCriterion("STORE_CLOSE_DATE not between", value1, value2, "storeCloseDate");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagIsNull() {
            addCriterion("STORE_SALES_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagIsNotNull() {
            addCriterion("STORE_SALES_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagEqualTo(String value) {
            addCriterion("STORE_SALES_FLAG =", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagNotEqualTo(String value) {
            addCriterion("STORE_SALES_FLAG <>", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagGreaterThan(String value) {
            addCriterion("STORE_SALES_FLAG >", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_SALES_FLAG >=", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagLessThan(String value) {
            addCriterion("STORE_SALES_FLAG <", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagLessThanOrEqualTo(String value) {
            addCriterion("STORE_SALES_FLAG <=", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagLike(String value) {
            addCriterion("STORE_SALES_FLAG like", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagNotLike(String value) {
            addCriterion("STORE_SALES_FLAG not like", value, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagIn(List<String> values) {
            addCriterion("STORE_SALES_FLAG in", values, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagNotIn(List<String> values) {
            addCriterion("STORE_SALES_FLAG not in", values, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagBetween(String value1, String value2) {
            addCriterion("STORE_SALES_FLAG between", value1, value2, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreSalesFlagNotBetween(String value1, String value2) {
            addCriterion("STORE_SALES_FLAG not between", value1, value2, "storeSalesFlag");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeIsNull() {
            addCriterion("STORE_ORGANAIZE is null");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeIsNotNull() {
            addCriterion("STORE_ORGANAIZE is not null");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeEqualTo(String value) {
            addCriterion("STORE_ORGANAIZE =", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeNotEqualTo(String value) {
            addCriterion("STORE_ORGANAIZE <>", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeGreaterThan(String value) {
            addCriterion("STORE_ORGANAIZE >", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ORGANAIZE >=", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeLessThan(String value) {
            addCriterion("STORE_ORGANAIZE <", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeLessThanOrEqualTo(String value) {
            addCriterion("STORE_ORGANAIZE <=", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeLike(String value) {
            addCriterion("STORE_ORGANAIZE like", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeNotLike(String value) {
            addCriterion("STORE_ORGANAIZE not like", value, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeIn(List<String> values) {
            addCriterion("STORE_ORGANAIZE in", values, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeNotIn(List<String> values) {
            addCriterion("STORE_ORGANAIZE not in", values, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeBetween(String value1, String value2) {
            addCriterion("STORE_ORGANAIZE between", value1, value2, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreOrganaizeNotBetween(String value1, String value2) {
            addCriterion("STORE_ORGANAIZE not between", value1, value2, "storeOrganaize");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromIsNull() {
            addCriterion("STORE_SYSTEM_FROM is null");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromIsNotNull() {
            addCriterion("STORE_SYSTEM_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_FROM =", value, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromNotEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_FROM <>", value, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromGreaterThan(Integer value) {
            addCriterion("STORE_SYSTEM_FROM >", value, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromGreaterThanOrEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_FROM >=", value, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromLessThan(Integer value) {
            addCriterion("STORE_SYSTEM_FROM <", value, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromLessThanOrEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_FROM <=", value, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromIn(List<Integer> values) {
            addCriterion("STORE_SYSTEM_FROM in", values, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromNotIn(List<Integer> values) {
            addCriterion("STORE_SYSTEM_FROM not in", values, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromBetween(Integer value1, Integer value2) {
            addCriterion("STORE_SYSTEM_FROM between", value1, value2, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemFromNotBetween(Integer value1, Integer value2) {
            addCriterion("STORE_SYSTEM_FROM not between", value1, value2, "storeSystemFrom");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToIsNull() {
            addCriterion("STORE_SYSTEM_TO is null");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToIsNotNull() {
            addCriterion("STORE_SYSTEM_TO is not null");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_TO =", value, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToNotEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_TO <>", value, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToGreaterThan(Integer value) {
            addCriterion("STORE_SYSTEM_TO >", value, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToGreaterThanOrEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_TO >=", value, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToLessThan(Integer value) {
            addCriterion("STORE_SYSTEM_TO <", value, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToLessThanOrEqualTo(Integer value) {
            addCriterion("STORE_SYSTEM_TO <=", value, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToIn(List<Integer> values) {
            addCriterion("STORE_SYSTEM_TO in", values, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToNotIn(List<Integer> values) {
            addCriterion("STORE_SYSTEM_TO not in", values, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToBetween(Integer value1, Integer value2) {
            addCriterion("STORE_SYSTEM_TO between", value1, value2, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreSystemToNotBetween(Integer value1, Integer value2) {
            addCriterion("STORE_SYSTEM_TO not between", value1, value2, "storeSystemTo");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnIsNull() {
            addCriterion("STORE_EXIST_KBN is null");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnIsNotNull() {
            addCriterion("STORE_EXIST_KBN is not null");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnEqualTo(String value) {
            addCriterion("STORE_EXIST_KBN =", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnNotEqualTo(String value) {
            addCriterion("STORE_EXIST_KBN <>", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnGreaterThan(String value) {
            addCriterion("STORE_EXIST_KBN >", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_EXIST_KBN >=", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnLessThan(String value) {
            addCriterion("STORE_EXIST_KBN <", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnLessThanOrEqualTo(String value) {
            addCriterion("STORE_EXIST_KBN <=", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnLike(String value) {
            addCriterion("STORE_EXIST_KBN like", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnNotLike(String value) {
            addCriterion("STORE_EXIST_KBN not like", value, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnIn(List<String> values) {
            addCriterion("STORE_EXIST_KBN in", values, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnNotIn(List<String> values) {
            addCriterion("STORE_EXIST_KBN not in", values, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnBetween(String value1, String value2) {
            addCriterion("STORE_EXIST_KBN between", value1, value2, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andStoreExistKbnNotBetween(String value1, String value2) {
            addCriterion("STORE_EXIST_KBN not between", value1, value2, "storeExistKbn");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIsNull() {
            addCriterion("ONLINE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIsNotNull() {
            addCriterion("ONLINE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineDateEqualTo(Integer value) {
            addCriterion("ONLINE_DATE =", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotEqualTo(Integer value) {
            addCriterion("ONLINE_DATE <>", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateGreaterThan(Integer value) {
            addCriterion("ONLINE_DATE >", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("ONLINE_DATE >=", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateLessThan(Integer value) {
            addCriterion("ONLINE_DATE <", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateLessThanOrEqualTo(Integer value) {
            addCriterion("ONLINE_DATE <=", value, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateIn(List<Integer> values) {
            addCriterion("ONLINE_DATE in", values, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotIn(List<Integer> values) {
            addCriterion("ONLINE_DATE not in", values, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateBetween(Integer value1, Integer value2) {
            addCriterion("ONLINE_DATE between", value1, value2, "onlineDate");
            return (Criteria) this;
        }

        public Criteria andOnlineDateNotBetween(Integer value1, Integer value2) {
            addCriterion("ONLINE_DATE not between", value1, value2, "onlineDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IY_STORE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IY_STORE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}