package cn.com.bbut.iy.itemmaster.entity.base;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import cn.com.bbut.iy.itemmaster.entity.BaseEntity;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Menu extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_MENU.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_MENU.PARENT_ID
     *
     * @mbg.generated
     */
    private Integer parentId;
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_MENU.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_MENU.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_MENU.SORT
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column IY_M_MENU.GROUP_CODE
     *
     * @mbg.generated
     */
    private String group;
}