package cn.com.bbut.iy.itemmaster.dto.ma4360;

import cn.com.bbut.iy.itemmaster.dto.base.GridDataDTO;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;


/**
 * 配方销售单商品详细 grid
 *
 * @author zcz
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Ma4360DetailGridDto extends GridDataDTO {
    /**
     * 传票号
     */
    private String voucherCd;

    /**
     * 商品id
     */
    private String articleId;

    /**
     * 商品名称
     */
    private String articleName;

    /**
     * 条码
     */
    private String barcode;

    /**
     * 售价
     */
    private BigDecimal salePrice;

    /**
     *  数量
     */
    private BigDecimal articleQty;

    /**
     *  售价金额
     */
    private BigDecimal salePriceAmount;

    /**
     * 规格
     */
    private String spec;

    /**
     * 单位
     */
    private String uom;

    /**
     * 备注
     */
    private String remark;
    /**
     * 数量
     */
    private String unitQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4350.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;

}
