package cn.com.bbut.iy.itemmaster.entity.ma1100;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA1100 extends MA1100Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.effective_end_date
     *
     * @mbggenerated
     */
    private String effectiveEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_name
     *
     * @mbggenerated
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_short_name
     *
     * @mbggenerated
     */
    private String articleShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_name_en
     *
     * @mbggenerated
     */
    private String articleNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_short_name_en
     *
     * @mbggenerated
     */
    private String articleShortNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.delivery_type_cd
     *
     * @mbggenerated
     */
    private String deliveryTypeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.dep_cd
     *
     * @mbggenerated
     */
    private String depCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.pma_cd
     *
     * @mbggenerated
     */
    private String pmaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.category_cd
     *
     * @mbggenerated
     */
    private String categoryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.sub_category_cd
     *
     * @mbggenerated
     */
    private String subCategoryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.spec
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.sales_unit_id
     *
     * @mbggenerated
     */
    private String salesUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.production_location
     *
     * @mbggenerated
     */
    private String productionLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.pb_flg
     *
     * @mbggenerated
     */
    private String pbFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.especial_flg
     *
     * @mbggenerated
     */
    private String especialFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_weigh_flag
     *
     * @mbggenerated
     */
    private String articleWeighFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_type
     *
     * @mbggenerated
     */
    private String articleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_new_flag
     *
     * @mbggenerated
     */
    private String articleNewFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.store_price_chg_flg
     *
     * @mbggenerated
     */
    private String storePriceChgFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.tag_type
     *
     * @mbggenerated
     */
    private String tagType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.season_cd
     *
     * @mbggenerated
     */
    private String seasonCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.lifecycle_status
     *
     * @mbggenerated
     */
    private String lifecycleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.recommend_reason_cd
     *
     * @mbggenerated
     */
    private String recommendReasonCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.receive_unit_id
     *
     * @mbggenerated
     */
    private String receiveUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_number
     *
     * @mbggenerated
     */
    private BigDecimal packageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.opl_method
     *
     * @mbggenerated
     */
    private String oplMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.min_display_qty
     *
     * @mbggenerated
     */
    private BigDecimal minDisplayQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.barcode_type
     *
     * @mbggenerated
     */
    private String barcodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.tenant_contract_no
     *
     * @mbggenerated
     */
    private String tenantContractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.sales_vat_cd
     *
     * @mbggenerated
     */
    private String salesVatCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.purchase_vat_cd
     *
     * @mbggenerated
     */
    private String purchaseVatCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.refer_purchase_price
     *
     * @mbggenerated
     */
    private BigDecimal referPurchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.refer_sale_price
     *
     * @mbggenerated
     */
    private BigDecimal referSalePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.preserve_type
     *
     * @mbggenerated
     */
    private String preserveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.warranty_days
     *
     * @mbggenerated
     */
    private BigDecimal warrantyDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.receive_date_limit
     *
     * @mbggenerated
     */
    private BigDecimal receiveDateLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.sale_date_limit
     *
     * @mbggenerated
     */
    private BigDecimal saleDateLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_os_weight
     *
     * @mbggenerated
     */
    private BigDecimal packageOsWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_os_size_length
     *
     * @mbggenerated
     */
    private BigDecimal packageOsSizeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_os_size_width
     *
     * @mbggenerated
     */
    private BigDecimal packageOsSizeWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_os_size_height
     *
     * @mbggenerated
     */
    private BigDecimal packageOsSizeHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_is_weight
     *
     * @mbggenerated
     */
    private BigDecimal packageIsWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_is_size_length
     *
     * @mbggenerated
     */
    private BigDecimal packageIsSizeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_is_size_width
     *
     * @mbggenerated
     */
    private BigDecimal packageIsSizeWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.package_is_size_height
     *
     * @mbggenerated
     */
    private BigDecimal packageIsSizeHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.create_ymd
     *
     * @mbggenerated
     */
    private String createYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.create_hms
     *
     * @mbggenerated
     */
    private String createHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.update_user_id
     *
     * @mbggenerated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.update_ymd
     *
     * @mbggenerated
     */
    private String updateYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.update_hms
     *
     * @mbggenerated
     */
    private String updateHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.update_screen_id
     *
     * @mbggenerated
     */
    private String updateScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.update_ip_address
     *
     * @mbggenerated
     */
    private String updateIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.nr_update_flg
     *
     * @mbggenerated
     */
    private String nrUpdateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.nr_ymd
     *
     * @mbggenerated
     */
    private String nrYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.nr_hms
     *
     * @mbggenerated
     */
    private String nrHms;
}