package cn.com.bbut.iy.itemmaster.entity.ma1100;
import lombok.Data;

@Data
public class MA1100Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1100.effective_start_date
     *
     * @mbggenerated
     */
    private String effectiveStartDate;
}