package cn.com.bbut.iy.itemmaster.dto.store;

import cn.com.bbut.iy.itemmaster.dto.base.GridParamDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * @ClassName MA4160ParamDTO
 * @Description TODO
 * @Author Administrator
 * @Date 2020/3/5 13:26
 * @Version 1.0
 */
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class MA4160ParamDTO  extends GridParamDTO {

    private int limitStart;
    private String jobTypeCd;
    private String jobCatagoryName;
    private String effectiveSts;
    private String createUserId;
    private String createYmd;
    private String createHms;
    private String updateUserId;
    private String updateYmd;
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4160.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4160.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4160.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4160.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4160.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;

    @Override
    public int getLimitStart() {
        return limitStart;
    }

    public void setLimitStart(int limitStart) {
        this.limitStart = limitStart;
    }

    public String getJobTypeCd() {
        return jobTypeCd;
    }

    public void setJobTypeCd(String jobTypeCd) {
        this.jobTypeCd = jobTypeCd;
    }

    public String getJobCatagoryName() {
        return jobCatagoryName;
    }

    public void setJobCatagoryName(String jobCatagoryName) {
        this.jobCatagoryName = jobCatagoryName;
    }

    public String getEffectiveSts() {
        return effectiveSts;
    }

    public void setEffectiveSts(String effectiveSts) {
        this.effectiveSts = effectiveSts;
    }

    public String getCreateUserId() {
        return createUserId;
    }

    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    public String getCreateYmd() {
        return createYmd;
    }

    public void setCreateYmd(String createYmd) {
        this.createYmd = createYmd;
    }

    public String getCreateHms() {
        return createHms;
    }

    public void setCreateHms(String createHms) {
        this.createHms = createHms;
    }

    public String getUpdateUserId() {
        return updateUserId;
    }

    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    public String getUpdateYmd() {
        return updateYmd;
    }

    public void setUpdateYmd(String updateYmd) {
        this.updateYmd = updateYmd;
    }

    public String getUpdateHms() {
        return updateHms;
    }

    public void setUpdateHms(String updateHms) {
        this.updateHms = updateHms;
    }

    public String getUpdateScreenId() {
        return updateScreenId;
    }

    public void setUpdateScreenId(String updateScreenId) {
        this.updateScreenId = updateScreenId;
    }

    public String getUpdateIpAddress() {
        return updateIpAddress;
    }

    public void setUpdateIpAddress(String updateIpAddress) {
        this.updateIpAddress = updateIpAddress;
    }

    public String getNrUpdateFlg() {
        return nrUpdateFlg;
    }

    public void setNrUpdateFlg(String nrUpdateFlg) {
        this.nrUpdateFlg = nrUpdateFlg;
    }

    public String getNrYmd() {
        return nrYmd;
    }

    public void setNrYmd(String nrYmd) {
        this.nrYmd = nrYmd;
    }

    public String getNrHms() {
        return nrHms;
    }

    public void setNrHms(String nrHms) {
        this.nrHms = nrHms;
    }
}
