package cn.com.bbut.iy.itemmaster.entity.sa0160;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class SA0160 extends SA0160Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.pos_name
     *
     * @mbg.generated
     */
    private String posName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.ip_address
     *
     * @mbg.generated
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.mac_address
     *
     * @mbg.generated
     */
    private String macAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.active_sts
     *
     * @mbg.generated
     */
    private String activeSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.online_time
     *
     * @mbg.generated
     */
    private Date onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.md_download_flg
     *
     * @mbg.generated
     */
    private String mdDownloadFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.price_chg_download_flg
     *
     * @mbg.generated
     */
    private String priceChgDownloadFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0160.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;
}