[#ftl]
[#import "/spring.ftl" as spring/]
[#global  syspath]
[@spring.message "common.syspath" /]
[/#global]
[#global  springpath]
[@spring.message "common.springpath" /]
[/#global]
[#global  staticpath]
[@spring.message "common.staticpath" /]
[/#global]
[#global title]
[@spring.message "common.title" /]
[/#global]
[#--
 *
 * load public page
 *
 --]
[#macro header]
  [#include "header.ftl" /]
[/#macro]
[#macro footer]
  [#include "footer.ftl" /]
[/#macro]
[#macro nav text]
  [#include "nav.ftl" /]
[/#macro]
[#macro menu]
  [#include "menu.ftl" /]
[/#macro]
[#macro user]
  [#include "userinfo.ftl" /]
[/#macro]
[#macro  selectStore divId storeList]
  [#include "selectStores.ftl" /]
[/#macro]
[#macro review]
  [#include "review.ftl" /]
[/#macro]
[#macro audit]
  [#include "audit.ftl" /]
[/#macro]
[#macro approvalRecords]
  [#include "approvalRecords.ftl" /]
[/#macro]
[#macro attachments]
  [#include "attachments.ftl" /]
[/#macro]
[#macro upload]
  [#include "upload.ftl" /]
[/#macro]