package cn.com.bbut.iy.itemmaster.entity.ma2000;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA2000 extends MA2000Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.effective_end_date
     *
     * @mbggenerated
     */
    private String effectiveEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_name
     *
     * @mbggenerated
     */
    private String vendorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_name_short
     *
     * @mbggenerated
     */
    private String vendorNameShort;
    /**
     * 供应商邮箱
     */
    private String vendorEmail;
    /**
     * 订货截止时间
     */
    private String cutoffTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.behalf_vendor_id
     *
     * @mbggenerated
     */
    private String behalfVendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.business_type
     *
     * @mbggenerated
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.trade_start_date
     *
     * @mbggenerated
     */
    private String tradeStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.trade_end_date
     *
     * @mbggenerated
     */
    private String tradeEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_flg
     *
     * @mbggenerated
     */
    private String orderFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_district_cd
     *
     * @mbggenerated
     */
    private String vendorDistrictCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_address1
     *
     * @mbggenerated
     */
    private String vendorAddress1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_address2
     *
     * @mbggenerated
     */
    private String vendorAddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_tel_no
     *
     * @mbggenerated
     */
    private String vendorTelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_fax_no
     *
     * @mbggenerated
     */
    private String vendorFaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.vendor_zip_code
     *
     * @mbggenerated
     */
    private String vendorZipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.admin_name
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_tel_no
     *
     * @mbggenerated
     */
    private String orderTelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_fax_no
     *
     * @mbggenerated
     */
    private String orderFaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.district_cd
     *
     * @mbggenerated
     */
    private String districtCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_address1
     *
     * @mbggenerated
     */
    private String orderAddress1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_address2
     *
     * @mbggenerated
     */
    private String orderAddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_admin_name
     *
     * @mbggenerated
     */
    private String orderAdminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.min_order_amt_tax
     *
     * @mbggenerated
     */
    private BigDecimal minOrderAmtTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.order_send_method
     *
     * @mbggenerated
     */
    private String orderSendMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.supply_purchase_rate
     *
     * @mbggenerated
     */
    private BigDecimal supplyPurchaseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.bad_discount_rate
     *
     * @mbggenerated
     */
    private BigDecimal badDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.shipment_flg
     *
     * @mbggenerated
     */
    private String shipmentFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_type_cd
     *
     * @mbggenerated
     */
    private String payTypeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_period_cd
     *
     * @mbggenerated
     */
    private String payPeriodCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_bank
     *
     * @mbggenerated
     */
    private String payBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_bank_account
     *
     * @mbggenerated
     */
    private String payBankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_account_name
     *
     * @mbggenerated
     */
    private String payAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_tax_no
     *
     * @mbggenerated
     */
    private String payTaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.pay_currency_type
     *
     * @mbggenerated
     */
    private String payCurrencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.create_ymd
     *
     * @mbggenerated
     */
    private String createYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.create_hms
     *
     * @mbggenerated
     */
    private String createHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.update_user_id
     *
     * @mbggenerated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.update_ymd
     *
     * @mbggenerated
     */
    private String updateYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.update_hms
     *
     * @mbggenerated
     */
    private String updateHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.update_screen_id
     *
     * @mbggenerated
     */
    private String updateScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.update_ip_address
     *
     * @mbggenerated
     */
    private String updateIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.nr_update_flg
     *
     * @mbggenerated
     */
    private String nrUpdateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.nr_ymd
     *
     * @mbggenerated
     */
    private String nrYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma2000.nr_hms
     *
     * @mbggenerated
     */
    private String nrHms;

    /**
     * 最低订货数量
     */
    private BigDecimal minOrderQty;
}