package cn.com.bbut.iy.itemmaster.entity.cm9000;

import java.util.ArrayList;
import java.util.List;

public class Cm9000Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected boolean needFoundRows = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public Cm9000Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public void setNeedFoundRows(boolean needFoundRows) {
        this.needFoundRows=needFoundRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public boolean getNeedFoundRows() {
        return needFoundRows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeTypeIsNull() {
            addCriterion("code_type is null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNotNull() {
            addCriterion("code_type is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeEqualTo(String value) {
            addCriterion("code_type =", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotEqualTo(String value) {
            addCriterion("code_type <>", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThan(String value) {
            addCriterion("code_type >", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("code_type >=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThan(String value) {
            addCriterion("code_type <", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThanOrEqualTo(String value) {
            addCriterion("code_type <=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLike(String value) {
            addCriterion("code_type like", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotLike(String value) {
            addCriterion("code_type not like", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIn(List<String> values) {
            addCriterion("code_type in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotIn(List<String> values) {
            addCriterion("code_type not in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeBetween(String value1, String value2) {
            addCriterion("code_type between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotBetween(String value1, String value2) {
            addCriterion("code_type not between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameIsNull() {
            addCriterion("code_type_name is null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameIsNotNull() {
            addCriterion("code_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameEqualTo(String value) {
            addCriterion("code_type_name =", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameNotEqualTo(String value) {
            addCriterion("code_type_name <>", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameGreaterThan(String value) {
            addCriterion("code_type_name >", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("code_type_name >=", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameLessThan(String value) {
            addCriterion("code_type_name <", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameLessThanOrEqualTo(String value) {
            addCriterion("code_type_name <=", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameLike(String value) {
            addCriterion("code_type_name like", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameNotLike(String value) {
            addCriterion("code_type_name not like", value, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameIn(List<String> values) {
            addCriterion("code_type_name in", values, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameNotIn(List<String> values) {
            addCriterion("code_type_name not in", values, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameBetween(String value1, String value2) {
            addCriterion("code_type_name between", value1, value2, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNameNotBetween(String value1, String value2) {
            addCriterion("code_type_name not between", value1, value2, "codeTypeName");
            return (Criteria) this;
        }

        public Criteria andDigitIsNull() {
            addCriterion("digit is null");
            return (Criteria) this;
        }

        public Criteria andDigitIsNotNull() {
            addCriterion("digit is not null");
            return (Criteria) this;
        }

        public Criteria andDigitEqualTo(Integer value) {
            addCriterion("digit =", value, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitNotEqualTo(Integer value) {
            addCriterion("digit <>", value, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitGreaterThan(Integer value) {
            addCriterion("digit >", value, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitGreaterThanOrEqualTo(Integer value) {
            addCriterion("digit >=", value, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitLessThan(Integer value) {
            addCriterion("digit <", value, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitLessThanOrEqualTo(Integer value) {
            addCriterion("digit <=", value, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitIn(List<Integer> values) {
            addCriterion("digit in", values, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitNotIn(List<Integer> values) {
            addCriterion("digit not in", values, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitBetween(Integer value1, Integer value2) {
            addCriterion("digit between", value1, value2, "digit");
            return (Criteria) this;
        }

        public Criteria andDigitNotBetween(Integer value1, Integer value2) {
            addCriterion("digit not between", value1, value2, "digit");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsIsNull() {
            addCriterion("effective_sts is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsIsNotNull() {
            addCriterion("effective_sts is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsEqualTo(String value) {
            addCriterion("effective_sts =", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotEqualTo(String value) {
            addCriterion("effective_sts <>", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsGreaterThan(String value) {
            addCriterion("effective_sts >", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsGreaterThanOrEqualTo(String value) {
            addCriterion("effective_sts >=", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsLessThan(String value) {
            addCriterion("effective_sts <", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsLessThanOrEqualTo(String value) {
            addCriterion("effective_sts <=", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsLike(String value) {
            addCriterion("effective_sts like", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotLike(String value) {
            addCriterion("effective_sts not like", value, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsIn(List<String> values) {
            addCriterion("effective_sts in", values, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotIn(List<String> values) {
            addCriterion("effective_sts not in", values, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsBetween(String value1, String value2) {
            addCriterion("effective_sts between", value1, value2, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andEffectiveStsNotBetween(String value1, String value2) {
            addCriterion("effective_sts not between", value1, value2, "effectiveSts");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idEqualTo(String value) {
            addCriterion("create_user_id =", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idGreaterThan(String value) {
            addCriterion("create_user_id >", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idLessThan(String value) {
            addCriterion("create_user_id <", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idLike(String value) {
            addCriterion("create_user_id like", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idNotLike(String value) {
            addCriterion("create_user_id not like", value, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idIn(List<String> values) {
            addCriterion("create_user_id in", values, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_user_idNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "create_user_id");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdIsNull() {
            addCriterion("create_ymd is null");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdIsNotNull() {
            addCriterion("create_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdEqualTo(String value) {
            addCriterion("create_ymd =", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdNotEqualTo(String value) {
            addCriterion("create_ymd <>", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdGreaterThan(String value) {
            addCriterion("create_ymd >", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdGreaterThanOrEqualTo(String value) {
            addCriterion("create_ymd >=", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdLessThan(String value) {
            addCriterion("create_ymd <", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdLessThanOrEqualTo(String value) {
            addCriterion("create_ymd <=", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdLike(String value) {
            addCriterion("create_ymd like", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdNotLike(String value) {
            addCriterion("create_ymd not like", value, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdIn(List<String> values) {
            addCriterion("create_ymd in", values, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdNotIn(List<String> values) {
            addCriterion("create_ymd not in", values, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdBetween(String value1, String value2) {
            addCriterion("create_ymd between", value1, value2, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_ymdNotBetween(String value1, String value2) {
            addCriterion("create_ymd not between", value1, value2, "create_ymd");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsIsNull() {
            addCriterion("create_hms is null");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsIsNotNull() {
            addCriterion("create_hms is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsEqualTo(String value) {
            addCriterion("create_hms =", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsNotEqualTo(String value) {
            addCriterion("create_hms <>", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsGreaterThan(String value) {
            addCriterion("create_hms >", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsGreaterThanOrEqualTo(String value) {
            addCriterion("create_hms >=", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsLessThan(String value) {
            addCriterion("create_hms <", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsLessThanOrEqualTo(String value) {
            addCriterion("create_hms <=", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsLike(String value) {
            addCriterion("create_hms like", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsNotLike(String value) {
            addCriterion("create_hms not like", value, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsIn(List<String> values) {
            addCriterion("create_hms in", values, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsNotIn(List<String> values) {
            addCriterion("create_hms not in", values, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsBetween(String value1, String value2) {
            addCriterion("create_hms between", value1, value2, "create_hms");
            return (Criteria) this;
        }

        public Criteria andCreate_hmsNotBetween(String value1, String value2) {
            addCriterion("create_hms not between", value1, value2, "create_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idEqualTo(String value) {
            addCriterion("update_user_id =", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idGreaterThan(String value) {
            addCriterion("update_user_id >", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idLessThan(String value) {
            addCriterion("update_user_id <", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idLike(String value) {
            addCriterion("update_user_id like", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idNotLike(String value) {
            addCriterion("update_user_id not like", value, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idIn(List<String> values) {
            addCriterion("update_user_id in", values, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_user_idNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "update_user_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdIsNull() {
            addCriterion("update_ymd is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdIsNotNull() {
            addCriterion("update_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdEqualTo(String value) {
            addCriterion("update_ymd =", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdNotEqualTo(String value) {
            addCriterion("update_ymd <>", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdGreaterThan(String value) {
            addCriterion("update_ymd >", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdGreaterThanOrEqualTo(String value) {
            addCriterion("update_ymd >=", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdLessThan(String value) {
            addCriterion("update_ymd <", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdLessThanOrEqualTo(String value) {
            addCriterion("update_ymd <=", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdLike(String value) {
            addCriterion("update_ymd like", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdNotLike(String value) {
            addCriterion("update_ymd not like", value, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdIn(List<String> values) {
            addCriterion("update_ymd in", values, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdNotIn(List<String> values) {
            addCriterion("update_ymd not in", values, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdBetween(String value1, String value2) {
            addCriterion("update_ymd between", value1, value2, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_ymdNotBetween(String value1, String value2) {
            addCriterion("update_ymd not between", value1, value2, "update_ymd");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsIsNull() {
            addCriterion("update_hms is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsIsNotNull() {
            addCriterion("update_hms is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsEqualTo(String value) {
            addCriterion("update_hms =", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsNotEqualTo(String value) {
            addCriterion("update_hms <>", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsGreaterThan(String value) {
            addCriterion("update_hms >", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsGreaterThanOrEqualTo(String value) {
            addCriterion("update_hms >=", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsLessThan(String value) {
            addCriterion("update_hms <", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsLessThanOrEqualTo(String value) {
            addCriterion("update_hms <=", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsLike(String value) {
            addCriterion("update_hms like", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsNotLike(String value) {
            addCriterion("update_hms not like", value, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsIn(List<String> values) {
            addCriterion("update_hms in", values, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsNotIn(List<String> values) {
            addCriterion("update_hms not in", values, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsBetween(String value1, String value2) {
            addCriterion("update_hms between", value1, value2, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_hmsNotBetween(String value1, String value2) {
            addCriterion("update_hms not between", value1, value2, "update_hms");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idIsNull() {
            addCriterion("update_screen_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idIsNotNull() {
            addCriterion("update_screen_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idEqualTo(String value) {
            addCriterion("update_screen_id =", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idNotEqualTo(String value) {
            addCriterion("update_screen_id <>", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idGreaterThan(String value) {
            addCriterion("update_screen_id >", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idGreaterThanOrEqualTo(String value) {
            addCriterion("update_screen_id >=", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idLessThan(String value) {
            addCriterion("update_screen_id <", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idLessThanOrEqualTo(String value) {
            addCriterion("update_screen_id <=", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idLike(String value) {
            addCriterion("update_screen_id like", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idNotLike(String value) {
            addCriterion("update_screen_id not like", value, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idIn(List<String> values) {
            addCriterion("update_screen_id in", values, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idNotIn(List<String> values) {
            addCriterion("update_screen_id not in", values, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idBetween(String value1, String value2) {
            addCriterion("update_screen_id between", value1, value2, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_screen_idNotBetween(String value1, String value2) {
            addCriterion("update_screen_id not between", value1, value2, "update_screen_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressIsNull() {
            addCriterion("update_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressIsNotNull() {
            addCriterion("update_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressEqualTo(String value) {
            addCriterion("update_ip_address =", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressNotEqualTo(String value) {
            addCriterion("update_ip_address <>", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressGreaterThan(String value) {
            addCriterion("update_ip_address >", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressGreaterThanOrEqualTo(String value) {
            addCriterion("update_ip_address >=", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressLessThan(String value) {
            addCriterion("update_ip_address <", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressLessThanOrEqualTo(String value) {
            addCriterion("update_ip_address <=", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressLike(String value) {
            addCriterion("update_ip_address like", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressNotLike(String value) {
            addCriterion("update_ip_address not like", value, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressIn(List<String> values) {
            addCriterion("update_ip_address in", values, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressNotIn(List<String> values) {
            addCriterion("update_ip_address not in", values, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressBetween(String value1, String value2) {
            addCriterion("update_ip_address between", value1, value2, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andUpdate_ip_addressNotBetween(String value1, String value2) {
            addCriterion("update_ip_address not between", value1, value2, "update_ip_address");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgIsNull() {
            addCriterion("nr_update_flg is null");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgIsNotNull() {
            addCriterion("nr_update_flg is not null");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgEqualTo(String value) {
            addCriterion("nr_update_flg =", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgNotEqualTo(String value) {
            addCriterion("nr_update_flg <>", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgGreaterThan(String value) {
            addCriterion("nr_update_flg >", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgGreaterThanOrEqualTo(String value) {
            addCriterion("nr_update_flg >=", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgLessThan(String value) {
            addCriterion("nr_update_flg <", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgLessThanOrEqualTo(String value) {
            addCriterion("nr_update_flg <=", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgLike(String value) {
            addCriterion("nr_update_flg like", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgNotLike(String value) {
            addCriterion("nr_update_flg not like", value, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgIn(List<String> values) {
            addCriterion("nr_update_flg in", values, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgNotIn(List<String> values) {
            addCriterion("nr_update_flg not in", values, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgBetween(String value1, String value2) {
            addCriterion("nr_update_flg between", value1, value2, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_update_flgNotBetween(String value1, String value2) {
            addCriterion("nr_update_flg not between", value1, value2, "nr_update_flg");
            return (Criteria) this;
        }

        public Criteria andNr_ymdIsNull() {
            addCriterion("nr_ymd is null");
            return (Criteria) this;
        }

        public Criteria andNr_ymdIsNotNull() {
            addCriterion("nr_ymd is not null");
            return (Criteria) this;
        }

        public Criteria andNr_ymdEqualTo(String value) {
            addCriterion("nr_ymd =", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdNotEqualTo(String value) {
            addCriterion("nr_ymd <>", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdGreaterThan(String value) {
            addCriterion("nr_ymd >", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdGreaterThanOrEqualTo(String value) {
            addCriterion("nr_ymd >=", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdLessThan(String value) {
            addCriterion("nr_ymd <", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdLessThanOrEqualTo(String value) {
            addCriterion("nr_ymd <=", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdLike(String value) {
            addCriterion("nr_ymd like", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdNotLike(String value) {
            addCriterion("nr_ymd not like", value, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdIn(List<String> values) {
            addCriterion("nr_ymd in", values, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdNotIn(List<String> values) {
            addCriterion("nr_ymd not in", values, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdBetween(String value1, String value2) {
            addCriterion("nr_ymd between", value1, value2, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_ymdNotBetween(String value1, String value2) {
            addCriterion("nr_ymd not between", value1, value2, "nr_ymd");
            return (Criteria) this;
        }

        public Criteria andNr_hmsIsNull() {
            addCriterion("nr_hms is null");
            return (Criteria) this;
        }

        public Criteria andNr_hmsIsNotNull() {
            addCriterion("nr_hms is not null");
            return (Criteria) this;
        }

        public Criteria andNr_hmsEqualTo(String value) {
            addCriterion("nr_hms =", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsNotEqualTo(String value) {
            addCriterion("nr_hms <>", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsGreaterThan(String value) {
            addCriterion("nr_hms >", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsGreaterThanOrEqualTo(String value) {
            addCriterion("nr_hms >=", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsLessThan(String value) {
            addCriterion("nr_hms <", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsLessThanOrEqualTo(String value) {
            addCriterion("nr_hms <=", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsLike(String value) {
            addCriterion("nr_hms like", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsNotLike(String value) {
            addCriterion("nr_hms not like", value, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsIn(List<String> values) {
            addCriterion("nr_hms in", values, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsNotIn(List<String> values) {
            addCriterion("nr_hms not in", values, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsBetween(String value1, String value2) {
            addCriterion("nr_hms between", value1, value2, "nr_hms");
            return (Criteria) this;
        }

        public Criteria andNr_hmsNotBetween(String value1, String value2) {
            addCriterion("nr_hms not between", value1, value2, "nr_hms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm9000
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm9000
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}