package cn.com.bbut.iy.itemmaster.entity.cm9010;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Cm9010 extends Cm9010Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.code_name
     *
     * @mbg.generated
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.default_value
     *
     * @mbg.generated
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.effective_sts
     *
     * @mbg.generated
     */
    private String effectiveSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.create_user_id
     *
     * @mbg.generated
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.create_ymd
     *
     * @mbg.generated
     */
    private String create_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.create_hms
     *
     * @mbg.generated
     */
    private String create_hms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.update_user_id
     *
     * @mbg.generated
     */
    private String update_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.update_ymd
     *
     * @mbg.generated
     */
    private String update_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.update_hms
     *
     * @mbg.generated
     */
    private String update_hms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.update_screen_id
     *
     * @mbg.generated
     */
    private String update_screen_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.update_ip_address
     *
     * @mbg.generated
     */
    private String update_ip_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.nr_update_flg
     *
     * @mbg.generated
     */
    private String nr_update_flg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.nr_ymd
     *
     * @mbg.generated
     */
    private String nr_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm9010.nr_hms
     *
     * @mbg.generated
     */
    private String nr_hms;
}