package cn.com.bbut.iy.itemmaster.entity.pi0010;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class PI0010 extends PI0010Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.barcode
     *
     * @mbggenerated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.sales_unit_id
     *
     * @mbggenerated
     */
    private String salesUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.dep_cd
     *
     * @mbggenerated
     */
    private String depCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.pma_cd
     *
     * @mbggenerated
     */
    private String pmaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.category_cd
     *
     * @mbggenerated
     */
    private String categoryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.sub_category_cd
     *
     * @mbggenerated
     */
    private String subCategoryCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.pi_qty_status
     *
     * @mbggenerated
     */
    private String piQtyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.first_qty
     *
     * @mbggenerated
     */
    private Integer firstQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.second_qty
     *
     * @mbggenerated
     */
    private Integer secondQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.on_hand_qty
     *
     * @mbggenerated
     */
    private Integer on_handQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.avg_cost_notax
     *
     * @mbggenerated
     */
    private Integer avgCostNotax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.sale_price
     *
     * @mbggenerated
     */
    private Integer salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.create_ymd
     *
     * @mbggenerated
     */
    private String createYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.create_hms
     *
     * @mbggenerated
     */
    private String createHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.update_user_id
     *
     * @mbggenerated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.update_ymd
     *
     * @mbggenerated
     */
    private String updateYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.update_hms
     *
     * @mbggenerated
     */
    private String updateHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.update_screen_id
     *
     * @mbggenerated
     */
    private String updateScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.update_ip_address
     *
     * @mbggenerated
     */
    private String updateIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.nr_update_flg
     *
     * @mbggenerated
     */
    private String nrUpdateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.nr_ymd
     *
     * @mbggenerated
     */
    private String nrYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi0010.nr_hms
     *
     * @mbggenerated
     */
    private String nrHms;
}