package cn.com.bbut.iy.itemmaster.entity.ma8230;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Ma8230 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.acc_date
     *
     * @mbg.generated
     */
    private String accDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather7b
     *
     * @mbg.generated
     */
    private String weather7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp7b
     *
     * @mbg.generated
     */
    private String maxtemp7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp7b
     *
     * @mbg.generated
     */
    private String mintemp7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather6b
     *
     * @mbg.generated
     */
    private String weather6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp6b
     *
     * @mbg.generated
     */
    private String maxtemp6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp6b
     *
     * @mbg.generated
     */
    private String mintemp6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather5b
     *
     * @mbg.generated
     */
    private String weather5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp5b
     *
     * @mbg.generated
     */
    private String maxtemp5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp5b
     *
     * @mbg.generated
     */
    private String mintemp5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather4b
     *
     * @mbg.generated
     */
    private String weather4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp4b
     *
     * @mbg.generated
     */
    private String maxtemp4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp4b
     *
     * @mbg.generated
     */
    private String mintemp4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather3b
     *
     * @mbg.generated
     */
    private String weather3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp3b
     *
     * @mbg.generated
     */
    private String maxtemp3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp3b
     *
     * @mbg.generated
     */
    private String mintemp3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather2b
     *
     * @mbg.generated
     */
    private String weather2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp2b
     *
     * @mbg.generated
     */
    private String maxtemp2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp2b
     *
     * @mbg.generated
     */
    private String mintemp2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather1b
     *
     * @mbg.generated
     */
    private String weather1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp1b
     *
     * @mbg.generated
     */
    private String maxtemp1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp1b
     *
     * @mbg.generated
     */
    private String mintemp1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather
     *
     * @mbg.generated
     */
    private String weather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp
     *
     * @mbg.generated
     */
    private String maxtemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp
     *
     * @mbg.generated
     */
    private String mintemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather1a
     *
     * @mbg.generated
     */
    private String weather1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp1a
     *
     * @mbg.generated
     */
    private String maxtemp1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp1a
     *
     * @mbg.generated
     */
    private String mintemp1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather2a
     *
     * @mbg.generated
     */
    private String weather2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp2a
     *
     * @mbg.generated
     */
    private String maxtemp2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp2a
     *
     * @mbg.generated
     */
    private String mintemp2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather3a
     *
     * @mbg.generated
     */
    private String weather3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp3a
     *
     * @mbg.generated
     */
    private String maxtemp3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp3a
     *
     * @mbg.generated
     */
    private String mintemp3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather4a
     *
     * @mbg.generated
     */
    private String weather4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp4a
     *
     * @mbg.generated
     */
    private String maxtemp4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp4a
     *
     * @mbg.generated
     */
    private String mintemp4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather5a
     *
     * @mbg.generated
     */
    private String weather5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp5a
     *
     * @mbg.generated
     */
    private String maxtemp5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp5a
     *
     * @mbg.generated
     */
    private String mintemp5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather6a
     *
     * @mbg.generated
     */
    private String weather6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp6a
     *
     * @mbg.generated
     */
    private String maxtemp6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp6a
     *
     * @mbg.generated
     */
    private String mintemp6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.weather7a
     *
     * @mbg.generated
     */
    private String weather7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.maxtemp7a
     *
     * @mbg.generated
     */
    private String maxtemp7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.mintemp7a
     *
     * @mbg.generated
     */
    private String mintemp7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.create_user_id
     *
     * @mbg.generated
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.create_ymd
     *
     * @mbg.generated
     */
    private String create_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.create_hms
     *
     * @mbg.generated
     */
    private String create_hms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.update_user_id
     *
     * @mbg.generated
     */
    private String update_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.update_ymd
     *
     * @mbg.generated
     */
    private String update_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.update_hms
     *
     * @mbg.generated
     */
    private String update_hms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.update_screen_id
     *
     * @mbg.generated
     */
    private String update_screen_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.update_ip_address
     *
     * @mbg.generated
     */
    private String update_ip_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.nr_update_flg
     *
     * @mbg.generated
     */
    private String nr_update_flg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.nr_ymd
     *
     * @mbg.generated
     */
    private String nr_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8230.nr_hms
     *
     * @mbg.generated
     */
    private String nr_hms;
}