package cn.com.bbut.iy.itemmaster.entity.ma4300;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA4300 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.inform_cd
     *
     * @mbg.generated
     */
    private String informCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.inform_title
     *
     * @mbg.generated
     */
    private String informTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.inform_content
     *
     * @mbg.generated
     */
    private String informContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.inform_start_date
     *
     * @mbg.generated
     */
    private String informStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.inform_end_date
     *
     * @mbg.generated
     */
    private String informEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4300.send_scope
     *
     * @mbg.generated
     */
    private String sendScope;

    /**
     * 店铺范围信息
     */
    private String storeDetailJson;
    /**
     * 附件信息
     */
    private String fileDetailJson;
    /**
     * 角色范围信息
     */
    private String roleDetailJson;
}