package cn.com.bbut.iy.itemmaster.dto.ma1105;

import cn.com.bbut.iy.itemmaster.dto.base.GridDataDTO;
import cn.com.bbut.iy.itemmaster.entity.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class Ma1105GridDataDTO extends GridDataDTO {
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.desc_g
     *
     * @mbg.generated
     */
    private String descG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.loc
     *
     * @mbg.generated
     */
    private String loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.v_facing
     *
     * @mbg.generated
     */
    private String vFacing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.h_facing
     *
     * @mbg.generated
     */
    private String hFacing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.d_facing
     *
     * @mbg.generated
     */
    private String dFacing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.total_facing
     *
     * @mbg.generated
     */
    private String totalFacing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.shelf
     *
     * @mbg.generated
     */
    private String shelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.sub_shelf
     *
     * @mbg.generated
     */
    private String subShelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma1105.create_date
     *
     * @mbg.generated
     */
    private Date createDate;
}