package cn.com.bbut.iy.itemmaster.dto.op0060;

import cn.com.bbut.iy.itemmaster.dto.base.GridDataDTO;
import cn.com.bbut.iy.itemmaster.dto.base.GridParamDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;


/**
 * OP0060grid
 *
 * @author zcz
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class OP0060GridDto  extends GridDataDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.acc_date
     *
     * @mbg.generated
     */
    private String accDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;
    /**
     * 店铺名称
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.delta_no
     *
     * @mbg.generated
     */
    private Integer deltaNo;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.pay_person
     *
     * @mbg.generated
     */
    private String payPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.pay_amt
     *
     * @mbg.generated
     */
    private BigDecimal payAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.record_sts
     *
     * @mbg.generated
     */
    private String recordSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column op0060.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;


    private String ofc;
    private String ofcName;
    private String oc;
    private String ocName;
    private String om;
    private String omName;
}
