package cn.com.bbut.iy.itemmaster.dto.sa0005;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * @ClassName SA0005ParamDTO
 * @Description TODO
 * @Author Administrator
 * @Date 2020/9/4 14:39
 * @Version 1.0
 */
@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class SA0005ParamDTO {

    private String posDisplayName;

    private String recordStatus;

    private String posDisplay;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.create_user_id
     *
     * @mbg.generated
     */
    private String  createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;
    private String payCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0005.pos_id
     *
     * @mbg.generated
     */
    private String posId;



    /**
     * 店铺名称
     */
    private String storeName;



    /**
     * pos name
     */
    private String posName;






}
