package cn.com.bbut.iy.itemmaster.entity.ma8240;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class Ma8240 extends Ma8240Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty7b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty7b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty7b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty7b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty7b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty6b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty6b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty6b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty6b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty6b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty5b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty5b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty5b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty5b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty5b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty4b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty4b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty4b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty4b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty4b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty3b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty3b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty3b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty3b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty3b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty2b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty2b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty2b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty2b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty2b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty1b
     *
     * @mbg.generated
     */
    private BigDecimal saleQty1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty1b
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty1b
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty1b
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty1b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty
     *
     * @mbg.generated
     */
    private BigDecimal saleQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty1a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty1a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty1a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty1a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty1a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty2a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty2a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty2a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty2a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty2a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty3a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty3a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty3a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty3a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty3a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty4a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty4a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty4a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty4a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty4a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty5a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty5a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty5a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty5a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty5a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty6a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty6a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty6a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty6a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty6a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.sale_qty7a
     *
     * @mbg.generated
     */
    private BigDecimal saleQty7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.receive_qty7a
     *
     * @mbg.generated
     */
    private BigDecimal receiveQty7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.adjust_qty7a
     *
     * @mbg.generated
     */
    private BigDecimal adjustQty7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.on_hand_qty7a
     *
     * @mbg.generated
     */
    private BigDecimal onHandQty7a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.create_user_id
     *
     * @mbg.generated
     */
    private String create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.create_ymd
     *
     * @mbg.generated
     */
    private String create_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.create_hms
     *
     * @mbg.generated
     */
    private String create_hms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.update_user_id
     *
     * @mbg.generated
     */
    private String update_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.update_ymd
     *
     * @mbg.generated
     */
    private String update_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.update_hms
     *
     * @mbg.generated
     */
    private String update_hms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.update_screen_id
     *
     * @mbg.generated
     */
    private String update_screen_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.update_ip_address
     *
     * @mbg.generated
     */
    private String update_ip_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.nr_update_flg
     *
     * @mbg.generated
     */
    private String nr_update_flg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.nr_ymd
     *
     * @mbg.generated
     */
    private String nr_ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma8240.nr_hms
     *
     * @mbg.generated
     */
    private String nr_hms;
}