package cn.com.bbut.iy.itemmaster.entity.ma0100;

import lombok.*;

import java.io.Serializable;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
@ToString(callSuper = true)
public class MA0100 extends MA0100Key implements Serializable {

    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.sub_category_name
     *
     * @mbggenerated
     */
    private String subCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.effective_sts
     *
     * @mbggenerated
     */
    private String effectiveSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.new_article_period
     *
     * @mbggenerated
     */
    private Integer newArticlePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.good_sale_dms
     *
     * @mbggenerated
     */
    private Integer goodSaleDms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.no_sale_day
     *
     * @mbggenerated
     */
    private Integer noSaleDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.create_ymd
     *
     * @mbggenerated
     */
    private String createYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.create_hms
     *
     * @mbggenerated
     */
    private String createHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.update_user_id
     *
     * @mbggenerated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.update_ymd
     *
     * @mbggenerated
     */
    private String updateYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.update_hms
     *
     * @mbggenerated
     */
    private String updateHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.update_screen_id
     *
     * @mbggenerated
     */
    private String updateScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.update_ip_address
     *
     * @mbggenerated
     */
    private String updateIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.nr_update_flg
     *
     * @mbggenerated
     */
    private String nrUpdateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.nr_ymd
     *
     * @mbggenerated
     */
    private String nrYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma0100.nr_hms
     *
     * @mbggenerated
     */
    private String nrHms;
}