package cn.com.bbut.iy.itemmaster.dto.ma4340;

import cn.com.bbut.iy.itemmaster.dto.base.AutoCompleteDTO;
import cn.com.bbut.iy.itemmaster.dto.base.GridParamDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;

/**
 *  新品信息 param
 *
 * @author zcz
 * @date:
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Ma4340DetailParamDto extends GridParamDTO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.launching_time
     *
     * @mbg.generated
     */
    private String launchingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.start_order_date
     *
     * @mbg.generated
     */
    private String startOrderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.vendor_id
     *
     * @mbg.generated
     */
    private String vendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.barcode
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.dep_cd
     *
     * @mbg.generated
     */
    private String depCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.selling_price
     *
     * @mbg.generated
     */
    private BigDecimal sellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.orgin
     *
     * @mbg.generated
     */
    private String orgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.shelf_life
     *
     * @mbg.generated
     */
    private String shelfLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.moq
     *
     * @mbg.generated
     */
    private String moq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.moa
     *
     * @mbg.generated
     */
    private String moa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.posm
     *
     * @mbg.generated
     */
    private String posm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_vendor_id
     *
     * @mbg.generated
     */
    private String descriptionVendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_item_code
     *
     * @mbg.generated
     */
    private String descriptionItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_barcode
     *
     * @mbg.generated
     */
    private String descriptionBarcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_product_name
     *
     * @mbg.generated
     */
    private String descriptionProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.descriptionOrder
     *
     * @mbg.generated
     */
    private String descriptionOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.order_method
     *
     * @mbg.generated
     */
    private String orderMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.order_schedule
     *
     * @mbg.generated
     */
    private String orderSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.display_position
     *
     * @mbg.generated
     */
    private String displayPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.bad_merchandise
     *
     * @mbg.generated
     */
    private String badMerchandise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.returnable
     *
     * @mbg.generated
     */
    private String returnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.exchange_goods
     *
     * @mbg.generated
     */
    private String exchangeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.sop
     *
     * @mbg.generated
     */
    private String sop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.selling_method
     *
     * @mbg.generated
     */
    private String sellingMethod;

    /**
     * 业务时间
     */
    private String businessDate;

    /**
     * 店铺CD
     */
    private String storeCd;
    /**
     * 店铺名称
     */
    private String storeName;

    /** 大区CD */
    private String regionCd;
    /** 城市CD */
    private String cityCd;
    /** 区域CD */
    private String districtCd;
    /** 权限包含的所有店铺编号 */
    private Collection<String> stores;
    /* 用户ID */
    private String userId;
    /* 通知标记 */
    private String informType;
}
