package cn.com.bbut.iy.itemmaster.dto.ma4340;

import cn.com.bbut.iy.itemmaster.dto.base.GridDataDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;


/**
 * 新品信息 grid
 *
 * @author zcz
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Ma4340DetailGridDto extends GridDataDTO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.launching_time
     *
     * @mbg.generated
     */
    private String launchingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.start_order_date
     *
     * @mbg.generated
     */
    private String startOrderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.vendor_id
     *
     * @mbg.generated
     */
    private String vendorId;

    /**
     *  供应商名称
     */
    private String vendorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.barcode
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.dep_cd
     *
     * @mbg.generated
     */
    private String depCd;

    /**
     *  中分类名称
     */
    private String pmaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.selling_price
     *
     * @mbg.generated
     */
    private BigDecimal sellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.orgin
     *
     * @mbg.generated
     */
    private String orgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.shelf_life
     *
     * @mbg.generated
     */
    private String shelfLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.moq
     *
     * @mbg.generated
     */
    private BigDecimal moq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.moa
     *
     * @mbg.generated
     */
    private BigDecimal moa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.posm
     *
     * @mbg.generated
     */
    private String posm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_vendor_id
     *
     * @mbg.generated
     */
    private String descriptionVendorId;



    /**
     *  供应商名称
     */
    private String descriptionVendorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_item_code
     *
     * @mbg.generated
     */
    private String descriptionItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_barcode
     *
     * @mbg.generated
     */
    private String descriptionBarcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.description_product_name
     *
     * @mbg.generated
     */
    private String descriptionProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.descriptionOrder
     *
     * @mbg.generated
     */
    private String descriptionOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.order_method
     *
     * @mbg.generated
     */
    private String orderMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.order_schedule
     *
     * @mbg.generated
     */
    private String orderSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.display_position
     *
     * @mbg.generated
     */
    private String displayPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.bad_merchandise
     *
     * @mbg.generated
     */
    private String badMerchandise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.returnable
     *
     * @mbg.generated
     */
    private String returnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.exchange_goods
     *
     * @mbg.generated
     */
    private String exchangeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.sop
     *
     * @mbg.generated
     */
    private String sop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4340.selling_method
     *
     * @mbg.generated
     */
    private String sellingMethod;

    private String storeCd;

    private String storeName;

    private String rowNum;
}
