package cn.com.bbut.iy.itemmaster.entity.od8030;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class OD8030 extends OD8030Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.barcode
     *
     * @mbggenerated
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.vendor_id
     *
     * @mbggenerated
     */
    private String vendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.receive_unit_id
     *
     * @mbggenerated
     */
    private String receiveUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.order_qty
     *
     * @mbggenerated
     */
    private BigDecimal orderQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.order_actual_qty
     *
     * @mbggenerated
     */
    private BigDecimal orderActualQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.order_nocharge_qty
     *
     * @mbggenerated
     */
    private BigDecimal orderNochargeQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.order_price
     *
     * @mbggenerated
     */
    private BigDecimal orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.upload_flg
     *
     * @mbggenerated
     */
    private String uploadFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.upload_date
     *
     * @mbggenerated
     */
    private String uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.display_seq
     *
     * @mbggenerated
     */
    private BigDecimal displaySeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.create_user_id
     *
     * @mbggenerated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.create_ymd
     *
     * @mbggenerated
     */
    private String createYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.create_hms
     *
     * @mbggenerated
     */
    private String createHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.update_user_id
     *
     * @mbggenerated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.update_ymd
     *
     * @mbggenerated
     */
    private String updateYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.update_hms
     *
     * @mbggenerated
     */
    private String updateHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.update_screen_id
     *
     * @mbggenerated
     */
    private String updateScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.update_ip_address
     *
     * @mbggenerated
     */
    private String updateIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.nr_update_flg
     *
     * @mbggenerated
     */
    private String nrUpdateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.nr_ymd
     *
     * @mbggenerated
     */
    private String nrYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.nr_hms
     *
     * @mbggenerated
     */
    private String nrHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.order_amount
     *
     * @mbggenerated
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od8030.reason
     *
     * @mbggenerated
     */
    private String reason;
}