package cn.com.bbut.iy.itemmaster.dto.ma4200;

import cn.com.bbut.iy.itemmaster.dto.base.GridDataDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class MA4200GridDTO  extends GridDataDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_num_id
     *
     * @mbg.generated
     */
    private String empNumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_id
     *
     * @mbg.generated
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;

    /**
     *  店铺名称
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.job_type_cd
     *
     * @mbg.generated
     */
    private String jobTypeCd;

    /**
     * 职务
     */
    private String jobCatagoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_password
     *
     * @mbg.generated
     */
    private String empPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.effective_status
     *
     * @mbg.generated
     */
    private String effectiveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_name
     *
     * @mbg.generated
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_gender
     *
     * @mbg.generated
     */
    private String empGender;

    /**
     * 性别
     */
    private String empGenderName;

    /**
     * 状态名称
     */
    private String effectiveStatusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_country
     *
     * @mbg.generated
     */
    private String empCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.telephone_no
     *
     * @mbg.generated
     */
    private String telephoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.mobile_phone_no
     *
     * @mbg.generated
     */
    private String mobilePhoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_birthdate
     *
     * @mbg.generated
     */
    private String empBirthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_education
     *
     * @mbg.generated
     */
    private String empEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_date
     *
     * @mbg.generated
     */
    private String empDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_leave_date
     *
     * @mbg.generated
     */
    private String empLeaveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_address
     *
     * @mbg.generated
     */
    private String empAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_postal_code
     *
     * @mbg.generated
     */
    private String empPostalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_comment
     *
     * @mbg.generated
     */
    private String empComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.emp_email
     *
     * @mbg.generated
     */
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ma4200.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;

    /**
     * 区分是否是md用户 1是
     */
    private String md;
}