/*
 Navicat Premium Data Transfer

 Source Server         : 119.23.201.148_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 110012
 Source Host           : nribits.vicp.io:46399
 Source Catalog        : storedb_store_uat
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 110012
 File Encoding         : 65001

 Date: 20/08/2021 10:30:43
*/


-- ----------------------------
-- Table structure for iy_m_permission
-- ----------------------------
DROP TABLE IF EXISTS "public"."iy_m_permission";
CREATE TABLE "public"."iy_m_permission" (
  "id" int4 NOT NULL DEFAULT nextval('iy_m_permission_id_seq'::regclass),
  "code" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "group_code" varchar(15) COLLATE "pg_catalog"."default" NOT NULL,
  "sort" int4 NOT NULL
)
;

-- ----------------------------
-- Records of iy_m_permission
-- ----------------------------
INSERT INTO "public"."iy_m_permission" VALUES (536, 'SC-MM-PROMOTION-001', 'View List', 'SC-MM-PROMOTION', 10);
INSERT INTO "public"."iy_m_permission" VALUES (537, 'SC-MM-PROMOTION-002', 'Print', 'SC-MM-PROMOTION', 20);
INSERT INTO "public"."iy_m_permission" VALUES (538, 'SC-MM-PROMOTION-003', 'Export', 'SC-MM-PROMOTION', 30);
INSERT INTO "public"."iy_m_permission" VALUES (511, 'SC-INVOICE-002', 'View', 'SC-INVOICE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (114, 'P-UAAS-002', 'Edit', 'P-UAAS', 20);
INSERT INTO "public"."iy_m_permission" VALUES (108, 'P-ROLE-003', 'Delete', 'P-ROLE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (107, 'P-ROLE-002', 'Edit', 'P-ROLE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (111, 'P-DEFASS-003', 'Cancel', 'P-ROLE-DEF', 30);
INSERT INTO "public"."iy_m_permission" VALUES (106, 'P-ROLE-001', 'View', 'P-ROLE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (115, 'P-UAAS-003', 'Cancel', 'P-UAAS', 30);
INSERT INTO "public"."iy_m_permission" VALUES (143, 'SC-DETAILS-001', 'View', 'SC-DETAILS', 10);
INSERT INTO "public"."iy_m_permission" VALUES (110, 'P-DEFASS-002', 'Edit', 'P-ROLE-DEF', 20);
INSERT INTO "public"."iy_m_permission" VALUES (243, 'SC-CASHIER-006', 'Restore Reset Password', 'SC-CASHIER', 60);
INSERT INTO "public"."iy_m_permission" VALUES (144, 'SC-DETAILS-002', 'Edit', 'SC-DETAILS', 20);
INSERT INTO "public"."iy_m_permission" VALUES (139, 'SC-DIFFERENCE-002', 'Modify', 'SC-DIFFERENCE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (145, 'SC-DETAILS-003', 'Add', 'SC-DETAILS', 30);
INSERT INTO "public"."iy_m_permission" VALUES (147, 'SC-DETAILS-006', 'Approval Records', 'SC-DETAILS', 50);
INSERT INTO "public"."iy_m_permission" VALUES (179, 'SC-PD-PROCESS-002', 'Print', 'SC-PD-PROCESS', 20);
INSERT INTO "public"."iy_m_permission" VALUES (137, 'SC-V-RECEIPT-005', 'Print', 'SC-V-RECEIPT', 50);
INSERT INTO "public"."iy_m_permission" VALUES (194, 'SC-RF-BOM-002', 'Print', 'SC-RF-BOM', 20);
INSERT INTO "public"."iy_m_permission" VALUES (493, 'SC-RETURNS-002', 'Print', 'SC-RETURNS', 20);
INSERT INTO "public"."iy_m_permission" VALUES (126, 'SC-RECEIPT-005', 'Print', 'SC-RECEIPT', 50);
INSERT INTO "public"."iy_m_permission" VALUES (222, 'SC-OD-FAILED-002', 'Export', 'SC-OD-FAILED', 50);
INSERT INTO "public"."iy_m_permission" VALUES (174, 'SC-PD-ENTRY-003', 'Export', 'SC-PD-ENTRY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (487, 'SC-JF-QUERY-001', 'View', 'SC-JF-QUERY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (128, 'SC-NS-ORDER-001', 'View', 'SC-NS-ORDER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (172, 'SC-PD-ENTRY-001', 'View', 'SC-PD-ENTRY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (178, 'SC-PD-PROCESS-001', 'View', 'SC-PD-PROCESS', 10);
INSERT INTO "public"."iy_m_permission" VALUES (122, 'SC-RECEIPT-001', 'View', 'SC-RECEIPT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (163, 'SC-ST-ADJUST-002', 'View', 'SC-ST-ADJUST', 20);
INSERT INTO "public"."iy_m_permission" VALUES (133, 'SC-V-RECEIPT-001', 'View', 'SC-V-RECEIPT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (153, 'SC-V-RETURN-001', 'View', 'SC-V-RETURN', 10);
INSERT INTO "public"."iy_m_permission" VALUES (148, 'SC-W-RETURN-001', 'View', 'SC-W-RETURN', 10);
INSERT INTO "public"."iy_m_permission" VALUES (130, 'SC-NS-ORDER-003', 'Delete', 'SC-NS-ORDER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (120, 'SC-ORDER-003', 'Delete', 'SC-ORDER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (164, 'SC-ST-ADJUST-003', 'Edit', 'SC-ST-ADJUST', 30);
INSERT INTO "public"."iy_m_permission" VALUES (118, 'SC-ORDER-001', 'View', 'SC-ORDER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (119, 'SC-ORDER-002', 'Edit', 'SC-ORDER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (129, 'SC-NS-ORDER-002', 'Edit', 'SC-NS-ORDER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (149, 'SC-W-RETURN-002', 'Modify', 'SC-W-RETURN', 20);
INSERT INTO "public"."iy_m_permission" VALUES (154, 'SC-V-RETURN-002', 'Modify', 'SC-V-RETURN', 20);
INSERT INTO "public"."iy_m_permission" VALUES (241, 'SC-CASHIER-004', 'Reactivate', 'SC-CASHIER', 40);
INSERT INTO "public"."iy_m_permission" VALUES (242, 'SC-CASHIER-005', 'Restore Initial Password', 'SC-CASHIER', 50);
INSERT INTO "public"."iy_m_permission" VALUES (496, 'SC-SUS-ENTRY-001', 'Edit', 'SC-SUS-ENTRY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (173, 'SC-PD-ENTRY-002', 'Edit', 'SC-PD-ENTRY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (123, 'SC-RECEIPT-002', 'Receiving', 'SC-RECEIPT', 20);
INSERT INTO "public"."iy_m_permission" VALUES (134, 'SC-V-RECEIPT-002', 'Receiving', 'SC-V-RECEIPT', 20);
INSERT INTO "public"."iy_m_permission" VALUES (264, 'SC-RR-MODIF-002', 'Edit', 'SC-RR-MODIF', 20);
INSERT INTO "public"."iy_m_permission" VALUES (135, 'SC-V-RECEIPT-003', 'Quick Receiving', 'SC-V-RECEIPT', 30);
INSERT INTO "public"."iy_m_permission" VALUES (124, 'SC-RECEIPT-003', 'Quick Receiving', 'SC-RECEIPT', 30);
INSERT INTO "public"."iy_m_permission" VALUES (161, 'SC-ST-TRANSFER-004', 'View List', 'SC-ST-TRANSFER', 40);
INSERT INTO "public"."iy_m_permission" VALUES (109, 'P-DEFASS-001', 'View List', 'P-ROLE-DEF', 10);
INSERT INTO "public"."iy_m_permission" VALUES (146, 'SC-DETAILS-004', 'View List', 'SC-DETAILS', 40);
INSERT INTO "public"."iy_m_permission" VALUES (113, 'P-UAAS-001', 'View List', 'P-UAAS', 10);
INSERT INTO "public"."iy_m_permission" VALUES (265, 'SC-RR-MODIF-003', 'View List', 'SC-RR-MODIF', 30);
INSERT INTO "public"."iy_m_permission" VALUES (125, 'SC-RECEIPT-004', 'View List', 'SC-RECEIPT', 40);
INSERT INTO "public"."iy_m_permission" VALUES (151, 'SC-W-RETURN-004', 'View List', 'SC-W-RETURN', 40);
INSERT INTO "public"."iy_m_permission" VALUES (112, 'P-ROLE-004', 'View List', 'P-ROLE', 40);
INSERT INTO "public"."iy_m_permission" VALUES (492, 'SC-RETURNS-001', 'View List', 'SC-RETURNS', 10);
INSERT INTO "public"."iy_m_permission" VALUES (156, 'SC-V-RETURN-004', 'View List', 'SC-V-RETURN', 40);
INSERT INTO "public"."iy_m_permission" VALUES (131, 'SC-NS-ORDER-004', 'View List', 'SC-NS-ORDER', 40);
INSERT INTO "public"."iy_m_permission" VALUES (136, 'SC-V-RECEIPT-004', 'View List', 'SC-V-RECEIPT', 40);
INSERT INTO "public"."iy_m_permission" VALUES (166, 'SC-ST-ADJUST-004', 'View List', 'SC-ST-ADJUST', 40);
INSERT INTO "public"."iy_m_permission" VALUES (177, 'SC-PD-ENTRY-006', 'View List', 'SC-PD-ENTRY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (513, 'SC-INVOICE-004', 'View List', 'SC-INVOICE', 40);
INSERT INTO "public"."iy_m_permission" VALUES (181, 'SC-PD-PROCESS-004', 'View List', 'SC-PD-PROCESS', 40);
INSERT INTO "public"."iy_m_permission" VALUES (504, 'SC-TODO-TASKS-001', 'View List', 'SC-TODO-TASKS', 10);
INSERT INTO "public"."iy_m_permission" VALUES (121, 'SC-ORDER-004', 'View List', 'SC-ORDER', 40);
INSERT INTO "public"."iy_m_permission" VALUES (253, 'SC-RECEIPTS-001', 'View List', 'SC-RECEIPTS', 10);
INSERT INTO "public"."iy_m_permission" VALUES (193, 'SC-RF-BOM-001', 'View List', 'SC-RF-BOM', 10);
INSERT INTO "public"."iy_m_permission" VALUES (333, 'SC-OFF-MANAGE-001', 'View List', 'SC-OFF-MANAGE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (410, 'SC-COST-ENTRY-006', 'Print', 'SC-COST-ENTRY', 60);
INSERT INTO "public"."iy_m_permission" VALUES (489, 'SC-JF-QUERY-003', 'Delete', 'SC-JF-QUERY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (520, 'SC-V-RETURN-007', 'Approval Records', 'SC-V-RETURN', 70);
INSERT INTO "public"."iy_m_permission" VALUES (185, 'SC-XS-USALE-004', 'Delete', 'SC-XS-USALE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (190, 'SC-XS-ORDER-003', 'Export', 'SC-XS-ORDER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (140, 'SC-DIFFERENCE-003', 'Add', 'SC-DIFFERENCE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (142, 'SC-DIFFERENCE-005', 'Export', 'SC-DIFFERENCE', 50);
INSERT INTO "public"."iy_m_permission" VALUES (380, 'SC-DIRECR-ORDER-003', 'Export', 'SC-DIRECR-ORDER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (379, 'SC-DIRECR-ORDER-002', 'Print', 'SC-DIRECR-ORDER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (363, 'SC-EM-INFOR-003', 'Modify', 'SC-EM-INFOR', 30);
INSERT INTO "public"."iy_m_permission" VALUES (374, 'SC-INF-HQ-002', 'Add', 'SC-INF-HQ', 20);
INSERT INTO "public"."iy_m_permission" VALUES (394, 'SC-INF-AUDIT-002', 'Approval Records', 'SC-INF-AUDIT', 20);
INSERT INTO "public"."iy_m_permission" VALUES (396, 'SC-INF-REJECTED-001', 'Approval Records', 'SC-INF-REJECTED', 10);
INSERT INTO "public"."iy_m_permission" VALUES (516, 'SC-ST-SCRAP-005', 'Approval Records', 'SC-ST-SCRAP', 50);
INSERT INTO "public"."iy_m_permission" VALUES (515, 'SC-ST-TRANSFER-005', 'Approval Records', 'SC-ST-TRANSFER', 50);
INSERT INTO "public"."iy_m_permission" VALUES (518, 'SC-W-RETURN-007', 'Approval Records', 'SC-W-RETURN', 70);
INSERT INTO "public"."iy_m_permission" VALUES (405, 'SC-COST-ENTRY-001', 'Add', 'SC-COST-ENTRY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (203, 'SC-JF-ENTRY-001', 'Add', 'SC-JF-ENTRY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (490, 'SC-JF-QUERY-004', 'Add', 'SC-JF-QUERY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (352, 'SC-PD-SETTING-001', 'Add', 'SC-PD-SETTING', 10);
INSERT INTO "public"."iy_m_permission" VALUES (349, 'SC-PM-002', 'Add', 'SC-PM', 20);
INSERT INTO "public"."iy_m_permission" VALUES (343, 'SC-SR-001', 'Add', 'SC-SR', 10);
INSERT INTO "public"."iy_m_permission" VALUES (168, 'SC-ST-SCRAP-001', 'Add', 'SC-ST-SCRAP', 10);
INSERT INTO "public"."iy_m_permission" VALUES (158, 'SC-ST-TRANSFER-001', 'Add', 'SC-ST-TRANSFER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (187, 'SC-XS-USALE-006', 'Export', 'SC-XS-USALE', 60);
INSERT INTO "public"."iy_m_permission" VALUES (409, 'SC-COST-ENTRY-005', 'Import', 'SC-COST-ENTRY', 50);
INSERT INTO "public"."iy_m_permission" VALUES (408, 'SC-COST-ENTRY-004', 'Export', 'SC-COST-ENTRY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (407, 'SC-COST-ENTRY-003', 'View', 'SC-COST-ENTRY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (406, 'SC-COST-ENTRY-002', 'Modify', 'SC-COST-ENTRY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (384, 'SC-ORDER-CD-002', 'Print', 'SC-ORDER-CD', 20);
INSERT INTO "public"."iy_m_permission" VALUES (517, 'SC-W-RETURN-006', 'Print', 'SC-W-RETURN', 60);
INSERT INTO "public"."iy_m_permission" VALUES (519, 'SC-V-RETURN-006', 'Print', 'SC-V-RETURN', 60);
INSERT INTO "public"."iy_m_permission" VALUES (385, 'SC-ORDER-CD-003', 'Export', 'SC-ORDER-CD', 30);
INSERT INTO "public"."iy_m_permission" VALUES (522, 'SC-ST-ADJUST-006', 'Export', 'SC-ST-ADJUST', 60);
INSERT INTO "public"."iy_m_permission" VALUES (523, 'SC-ST-SCRAP-006', 'Export', 'SC-ST-SCRAP', 60);
INSERT INTO "public"."iy_m_permission" VALUES (521, 'SC-ST-TRANSFER-006', 'Export', 'SC-ST-TRANSFER', 60);
INSERT INTO "public"."iy_m_permission" VALUES (354, 'SC-PD-SETTING-003', 'View', 'SC-PD-SETTING', 30);
INSERT INTO "public"."iy_m_permission" VALUES (263, 'SC-RR-MODIF-001', 'View', 'SC-RR-MODIF', 10);
INSERT INTO "public"."iy_m_permission" VALUES (338, 'SC-STORE-DAILY-001', 'View', 'SC-STORE-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (169, 'SC-ST-SCRAP-002', 'View', 'SC-ST-SCRAP', 20);
INSERT INTO "public"."iy_m_permission" VALUES (188, 'SC-XS-ORDER-001', 'View', 'SC-XS-ORDER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (183, 'SC-XS-USALE-002', 'View', 'SC-XS-USALE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (208, 'SC-ZD-BPQ-001', 'View', 'SC-ZD-BPQ', 10);
INSERT INTO "public"."iy_m_permission" VALUES (184, 'SC-XS-USALE-003', 'Modify', 'SC-XS-USALE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (323, 'SC-PRI-CAG-001', 'Edit', 'SC-PRI-CAG', 10);
INSERT INTO "public"."iy_m_permission" VALUES (369, 'SC-INF-REPLY-002', 'Reply', 'SC-INF-REPLY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (353, 'SC-PD-SETTING-002', 'Modify', 'SC-PD-SETTING', 20);
INSERT INTO "public"."iy_m_permission" VALUES (393, 'SC-INF-AUDIT-001', 'Approval', 'SC-INF-AUDIT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (170, 'SC-ST-SCRAP-003', 'Modify', 'SC-ST-SCRAP', 30);
INSERT INTO "public"."iy_m_permission" VALUES (350, 'SC-PM-003', 'Modify', 'SC-PM', 30);
INSERT INTO "public"."iy_m_permission" VALUES (360, 'SC-OR-STRUCT-001', 'View List', 'SC-OR-STRUCT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (512, 'SC-INVOICE-003', 'Issue Invoice', 'SC-INVOICE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (488, 'SC-JF-QUERY-002', 'Modify', 'SC-JF-QUERY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (159, 'SC-ST-TRANSFER-002', 'View', 'SC-ST-TRANSFER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (491, 'SC-JF-QUERY-005', 'View List', 'SC-JF-QUERY', 50);
INSERT INTO "public"."iy_m_permission" VALUES (500, 'SC-SUS-LIST-001', 'View List', 'SC-SUS-LIST', 10);
INSERT INTO "public"."iy_m_permission" VALUES (141, 'SC-DIFFERENCE-004', 'View List', 'SC-DIFFERENCE', 40);
INSERT INTO "public"."iy_m_permission" VALUES (366, 'SC-EM-INFOR-006', 'View List', 'SC-EM-INFOR', 60);
INSERT INTO "public"."iy_m_permission" VALUES (209, 'SC-ZD-BPQ-002', 'View List', 'SC-ZD-BPQ', 20);
INSERT INTO "public"."iy_m_permission" VALUES (328, 'SC-PRI-CHANGE-001', 'View List', 'SC-PRI-CHANGE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (189, 'SC-XS-ORDER-002', 'View List', 'SC-XS-ORDER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (201, 'SC-ZD-PBD-001', 'View List', 'SC-ZD-PBD', 10);
INSERT INTO "public"."iy_m_permission" VALUES (383, 'SC-ORDER-CD-001', 'View List', 'SC-ORDER-CD', 10);
INSERT INTO "public"."iy_m_permission" VALUES (397, 'SC-INF-REJECTED-002', 'View List', 'SC-INF-REJECTED', 20);
INSERT INTO "public"."iy_m_permission" VALUES (216, 'SC-ST-KCCPYL-003', 'View List', 'SC-ST-KCCPYL', 40);
INSERT INTO "public"."iy_m_permission" VALUES (182, 'SC-XS-USALE-001', 'View List', 'SC-XS-USALE', 40);
INSERT INTO "public"."iy_m_permission" VALUES (388, 'SC-INF-LOG-001', 'View List', 'SC-INF-LOG', 10);
INSERT INTO "public"."iy_m_permission" VALUES (320, 'SC-RW-003', 'View List', 'SC-RW', 30);
INSERT INTO "public"."iy_m_permission" VALUES (395, 'SC-INF-AUDIT-003', 'View List', 'SC-INF-AUDIT', 30);
INSERT INTO "public"."iy_m_permission" VALUES (370, 'SC-INF-REPLY-003', 'View List', 'SC-INF-REPLY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (376, 'SC-INF-HQ-003', 'View List', 'SC-INF-HQ', 30);
INSERT INTO "public"."iy_m_permission" VALUES (339, 'SC-STORE-DAILY-002', '门店销售日报 编辑权限', 'SC-STORE-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (469, 'SC-A-M-002', 'Print', 'SC-A-M', 20);
INSERT INTO "public"."iy_m_permission" VALUES (470, 'SC-A-M-003', 'Export', 'SC-A-M', 30);
INSERT INTO "public"."iy_m_permission" VALUES (459, 'SC-DC-DAILY-002', 'Print', 'SC-DC-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (460, 'SC-DC-DAILY-003', 'Export', 'SC-DC-DAILY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (361, 'SC-EM-INFOR-001', 'Add', 'SC-EM-INFOR', 10);
INSERT INTO "public"."iy_m_permission" VALUES (364, 'SC-EM-INFOR-004', 'View', 'SC-EM-INFOR', 40);
INSERT INTO "public"."iy_m_permission" VALUES (418, 'SC-FS-ENTRY-001', 'Add', 'SC-FS-ENTRY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (365, 'SC-EM-INFOR-005', 'Delete', 'SC-EM-INFOR', 50);
INSERT INTO "public"."iy_m_permission" VALUES (419, 'SC-FS-ENTRY-002', 'Modify', 'SC-FS-ENTRY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (422, 'SC-FS-ENTRY-005', 'Import', 'SC-FS-ENTRY', 50);
INSERT INTO "public"."iy_m_permission" VALUES (420, 'SC-FS-ENTRY-003', 'View', 'SC-FS-ENTRY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (421, 'SC-FS-ENTRY-004', 'Export', 'SC-FS-ENTRY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (423, 'SC-FS-ENTRY-006', 'Print', 'SC-FS-ENTRY', 60);
INSERT INTO "public"."iy_m_permission" VALUES (464, 'SC-GS-RE-002', 'Print', 'SC-GS-RE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (465, 'SC-GS-RE-003', 'Export', 'SC-GS-RE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (373, 'SC-INF-HQ-001', 'View', 'SC-INF-HQ', 10);
INSERT INTO "public"."iy_m_permission" VALUES (399, 'SC-INF-DOCUMENT-002', 'Approval Records', 'SC-INF-DOCUMENT', 20);
INSERT INTO "public"."iy_m_permission" VALUES (417, 'SC-FS-ENTRY-008', 'Approval Records', 'SC-FS-ENTRY', 80);
INSERT INTO "public"."iy_m_permission" VALUES (412, 'SC-COST-ENTRY-008', 'Approval Records', 'SC-COST-ENTRY', 80);
INSERT INTO "public"."iy_m_permission" VALUES (432, 'SC-MATEL-ENTRY-008', 'Approval Records', 'SC-MATEL-ENTRY', 80);
INSERT INTO "public"."iy_m_permission" VALUES (282, 'SC-PD-ENTRY-007', 'Approval Records', 'SC-PD-ENTRY', 70);
INSERT INTO "public"."iy_m_permission" VALUES (425, 'SC-MATEL-ENTRY-001', 'Add', 'SC-MATEL-ENTRY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (176, 'SC-PD-ENTRY-005', 'Print', 'SC-PD-ENTRY', 50);
INSERT INTO "public"."iy_m_permission" VALUES (449, 'SC-WRITE-OFF-002', 'Print', 'SC-WRITE-OFF', 20);
INSERT INTO "public"."iy_m_permission" VALUES (444, 'SC-VENDOR-DAILY-002', 'Print', 'SC-VENDOR-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (439, 'SC-STORE-SALE-002', 'Print', 'SC-STORE-SALE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (434, 'SC-STORE-DAY-002', 'Print', 'SC-STORE-DAY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (321, 'SC-RW-004', 'Print', 'SC-RW', 40);
INSERT INTO "public"."iy_m_permission" VALUES (272, 'SC-RR-QUERY-006', 'Print', 'SC-RR-QUERY', 60);
INSERT INTO "public"."iy_m_permission" VALUES (197, 'SC-RF-BOM-005', 'Export', 'SC-RF-BOM', 50);
INSERT INTO "public"."iy_m_permission" VALUES (445, 'SC-VENDOR-DAILY-003', 'Export', 'SC-VENDOR-DAILY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (157, 'SC-V-RETURN-005', 'Export', 'SC-V-RETURN', 50);
INSERT INTO "public"."iy_m_permission" VALUES (152, 'SC-W-RETURN-005', 'Export', 'SC-W-RETURN', 50);
INSERT INTO "public"."iy_m_permission" VALUES (368, 'SC-INF-REPLY-001', 'View', 'SC-INF-REPLY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (450, 'SC-WRITE-OFF-003', 'Export', 'SC-WRITE-OFF', 30);
INSERT INTO "public"."iy_m_permission" VALUES (427, 'SC-MATEL-ENTRY-003', 'View', 'SC-MATEL-ENTRY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (348, 'SC-PM-001', 'View', 'SC-PM', 10);
INSERT INTO "public"."iy_m_permission" VALUES (414, 'SC-PROMOTION-001', 'View', 'SC-PROMOTION', 10);
INSERT INTO "public"."iy_m_permission" VALUES (267, 'SC-RR-QUERY-001', 'View', 'SC-RR-QUERY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (345, 'SC-SR-003', 'Delete', 'SC-SR', 30);
INSERT INTO "public"."iy_m_permission" VALUES (340, 'SC-STORE-DAILY-003', 'Delete', 'SC-STORE-DAILY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (426, 'SC-MATEL-ENTRY-002', 'Modify', 'SC-MATEL-ENTRY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (428, 'SC-MATEL-ENTRY-004', 'Export', 'SC-MATEL-ENTRY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (429, 'SC-MATEL-ENTRY-005', 'Import', 'SC-MATEL-ENTRY', 50);
INSERT INTO "public"."iy_m_permission" VALUES (430, 'SC-MATEL-ENTRY-006', 'Print', 'SC-MATEL-ENTRY', 60);
INSERT INTO "public"."iy_m_permission" VALUES (398, 'SC-INF-DOCUMENT-001', 'Withdraw', 'SC-INF-DOCUMENT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (268, 'SC-RR-QUERY-002', 'Receiving', 'SC-RR-QUERY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (344, 'SC-SR-002', 'Modify', 'SC-SR', 20);
INSERT INTO "public"."iy_m_permission" VALUES (269, 'SC-RR-QUERY-003', 'Quick Receiving', 'SC-RR-QUERY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (413, 'SC-NEWPRODUCR-001', 'View List', 'SC-NEWPRODUCR', 10);
INSERT INTO "public"."iy_m_permission" VALUES (346, 'SC-SR-004', 'View List', 'SC-SR', 40);
INSERT INTO "public"."iy_m_permission" VALUES (175, 'SC-PD-ENTRY-004', 'Import', 'SC-PD-ENTRY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (362, 'SC-EM-INFOR-002', 'Reset Password', 'SC-EM-INFOR', 20);
INSERT INTO "public"."iy_m_permission" VALUES (358, 'SC-PD-SETTING-007', 'View List', 'SC-PD-SETTING', 70);
INSERT INTO "public"."iy_m_permission" VALUES (288, 'SC-RF-INVENTORY-001', 'View List', 'SC-RF-INVENTORY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (351, 'SC-PM-004', 'View List', 'SC-PM', 40);
INSERT INTO "public"."iy_m_permission" VALUES (453, 'SC-ADJUSTMENT-001', 'View List', 'SC-ADJUSTMENT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (433, 'SC-STORE-DAY-001', 'View List', 'SC-STORE-DAY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (438, 'SC-STORE-SALE-001', 'View List', 'SC-STORE-SALE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (411, 'SC-COST-ENTRY-007', 'View List', 'SC-COST-ENTRY', 70);
INSERT INTO "public"."iy_m_permission" VALUES (400, 'SC-INF-DOCUMENT-003', 'View List', 'SC-INF-DOCUMENT', 30);
INSERT INTO "public"."iy_m_permission" VALUES (403, 'SC-INF-MESSAGE-001', 'View List', 'SC-INF-MESSAGE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (341, 'SC-STORE-DAILY-004', 'View List', 'SC-STORE-DAILY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (458, 'SC-DC-DAILY-001', 'View List', 'SC-DC-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (443, 'SC-VENDOR-DAILY-001', 'View List', 'SC-VENDOR-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (448, 'SC-WRITE-OFF-001', 'View List', 'SC-WRITE-OFF', 10);
INSERT INTO "public"."iy_m_permission" VALUES (463, 'SC-GS-RE-001', 'View List', 'SC-GS-RE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (415, 'SC-PROMOTION-002', 'View List', 'SC-PROMOTION', 20);
INSERT INTO "public"."iy_m_permission" VALUES (468, 'SC-A-M-001', 'View List', 'SC-A-M', 10);
INSERT INTO "public"."iy_m_permission" VALUES (473, 'SC-TRANSFER-001', 'View List', 'SC-TRANSFER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (424, 'SC-FS-ENTRY-007', 'View List', 'SC-FS-ENTRY', 70);
INSERT INTO "public"."iy_m_permission" VALUES (319, 'SC-RW-002', 'Edit', 'SC-RW', 20);
INSERT INTO "public"."iy_m_permission" VALUES (239, 'SC-CASHIER-002', 'Modify Privilege', 'SC-CASHIER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (309, 'SC-PI-002', 'Modify', 'SC-PI', 20);
INSERT INTO "public"."iy_m_permission" VALUES (171, 'SC-ST-SCRAP-004', 'View List', 'SC-ST-SCRAP', 40);
INSERT INTO "public"."iy_m_permission" VALUES (296, 'P-MENU-004', 'View List', 'P-MENU', 40);
INSERT INTO "public"."iy_m_permission" VALUES (284, 'SC-BD-002', 'Print', 'SC-BD', 20);
INSERT INTO "public"."iy_m_permission" VALUES (303, 'SC-CA-001', 'Edit', 'SC-CA', 10);
INSERT INTO "public"."iy_m_permission" VALUES (138, 'SC-DIFFERENCE-001', 'View', 'SC-DIFFERENCE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (479, 'SC-IM-SALE-RE-002', 'Print', 'SC-IM-SALE-RE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (480, 'SC-IM-SALE-RE-003', 'Export', 'SC-IM-SALE-RE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (293, 'P-MENU-001', 'View', 'P-MENU', 10);
INSERT INTO "public"."iy_m_permission" VALUES (294, 'P-MENU-002', 'Edit', 'P-MENU', 20);
INSERT INTO "public"."iy_m_permission" VALUES (295, 'P-MENU-003', 'Delete', 'P-MENU', 30);
INSERT INTO "public"."iy_m_permission" VALUES (454, 'SC-ADJUSTMENT-002', 'Print', 'SC-ADJUSTMENT', 20);
INSERT INTO "public"."iy_m_permission" VALUES (455, 'SC-ADJUSTMENT-003', 'Export', 'SC-ADJUSTMENT', 30);
INSERT INTO "public"."iy_m_permission" VALUES (514, 'SC-PD-PROCESS-005', 'Approval Records', 'SC-PD-PROCESS', 50);
INSERT INTO "public"."iy_m_permission" VALUES (167, 'SC-ST-ADJUST-005', 'Approval Records', 'SC-ST-ADJUST', 50);
INSERT INTO "public"."iy_m_permission" VALUES (474, 'SC-TRANSFER-002', 'Print', 'SC-TRANSFER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (238, 'SC-CASHIER-001', 'Add', 'SC-CASHIER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (308, 'SC-PI-001', 'Add', 'SC-PI', 10);
INSERT INTO "public"."iy_m_permission" VALUES (162, 'SC-ST-ADJUST-001', 'Add', 'SC-ST-ADJUST', 10);
INSERT INTO "public"."iy_m_permission" VALUES (155, 'SC-V-RETURN-003', 'Add', 'SC-V-RETURN', 30);
INSERT INTO "public"."iy_m_permission" VALUES (150, 'SC-W-RETURN-003', 'Add', 'SC-W-RETURN', 30);
INSERT INTO "public"."iy_m_permission" VALUES (186, 'SC-XS-USALE-005', 'Add', 'SC-XS-USALE', 50);
INSERT INTO "public"."iy_m_permission" VALUES (484, 'SC-INVENTORY-002', 'Print', 'SC-INVENTORY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (316, 'SC-RV-004', 'Print', 'SC-RV', 40);
INSERT INTO "public"."iy_m_permission" VALUES (289, 'SC-RF-INVENTORY-002', 'Print', 'SC-RF-INVENTORY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (234, 'SC-RF-GROUP-002', 'Print', 'SC-RF-GROUP', 20);
INSERT INTO "public"."iy_m_permission" VALUES (355, 'SC-PD-SETTING-004', 'Print', 'SC-PD-SETTING', 40);
INSERT INTO "public"."iy_m_permission" VALUES (485, 'SC-INVENTORY-003', 'Export', 'SC-INVENTORY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (180, 'SC-PD-PROCESS-003', 'Export', 'SC-PD-PROCESS', 30);
INSERT INTO "public"."iy_m_permission" VALUES (356, 'SC-PD-SETTING-005', 'Export', 'SC-PD-SETTING', 50);
INSERT INTO "public"."iy_m_permission" VALUES (357, 'SC-PD-SETTING-006', 'Export', 'SC-PD-SETTING', 60);
INSERT INTO "public"."iy_m_permission" VALUES (494, 'SC-RETURNS-003', 'Export', 'SC-RETURNS', 30);
INSERT INTO "public"."iy_m_permission" VALUES (237, 'SC-RF-GROUP-005', 'Export', 'SC-RF-GROUP', 50);
INSERT INTO "public"."iy_m_permission" VALUES (290, 'SC-RF-INVENTORY-003', 'Export', 'SC-RF-INVENTORY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (271, 'SC-RR-QUERY-005', 'Export', 'SC-RR-QUERY', 50);
INSERT INTO "public"."iy_m_permission" VALUES (300, 'SC-S-I-R-003', 'Export', 'SC-S-I-R', 30);
INSERT INTO "public"."iy_m_permission" VALUES (274, 'SC-SL-CF-002', 'Export', 'SC-SL-CF', 20);
INSERT INTO "public"."iy_m_permission" VALUES (217, 'SC-ST-KCCPYL-004', 'Export', 'SC-ST-KCCPYL', 50);
INSERT INTO "public"."iy_m_permission" VALUES (435, 'SC-STORE-DAY-003', 'Export', 'SC-STORE-DAY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (475, 'SC-TRANSFER-003', 'Export', 'SC-TRANSFER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (210, 'SC-ZD-BPQ-003', 'Export', 'SC-ZD-BPQ', 30);
INSERT INTO "public"."iy_m_permission" VALUES (226, 'SC-ZD-IMQ-003', 'Export', 'SC-ZD-IMQ', 30);
INSERT INTO "public"."iy_m_permission" VALUES (202, 'SC-ZD-PBD-002', 'Export', 'SC-ZD-PBD', 20);
INSERT INTO "public"."iy_m_permission" VALUES (230, 'SC-ZD-VMQ-003', 'Export', 'SC-ZD-VMQ', 30);
INSERT INTO "public"."iy_m_permission" VALUES (313, 'SC-RV-001', 'View', 'SC-RV', 10);
INSERT INTO "public"."iy_m_permission" VALUES (318, 'SC-RW-001', 'View', 'SC-RW', 10);
INSERT INTO "public"."iy_m_permission" VALUES (214, 'SC-ST-KCCPYL-001', 'View', 'SC-ST-KCCPYL', 10);
INSERT INTO "public"."iy_m_permission" VALUES (224, 'SC-ZD-IMQ-001', 'View', 'SC-ZD-IMQ', 10);
INSERT INTO "public"."iy_m_permission" VALUES (228, 'SC-ZD-VMQ-001', 'View', 'SC-ZD-VMQ', 10);
INSERT INTO "public"."iy_m_permission" VALUES (310, 'SC-PI-003', 'Delete', 'SC-PI', 30);
INSERT INTO "public"."iy_m_permission" VALUES (215, 'SC-ST-KCCPYL-002', 'Edit', 'SC-ST-KCCPYL', 20);
INSERT INTO "public"."iy_m_permission" VALUES (299, 'SC-S-I-R-002', 'Import', 'SC-S-I-R', 20);
INSERT INTO "public"."iy_m_permission" VALUES (378, 'SC-DIRECR-ORDER-001', 'View List', 'SC-DIRECR-ORDER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (261, 'SC-RR-MODIF-E-001', 'Add', 'SC-RR-MODIF-E', 10);
INSERT INTO "public"."iy_m_permission" VALUES (240, 'SC-CASHIER-003', 'Eliminate', 'SC-CASHIER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (262, 'SC-RR-MODIF-E-002', 'View', 'SC-RR-MODIF-E', 20);
INSERT INTO "public"."iy_m_permission" VALUES (160, 'SC-ST-TRANSFER-003', 'Modify', 'SC-ST-TRANSFER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (314, 'SC-RV-002', 'Edit', 'SC-RV', 20);
INSERT INTO "public"."iy_m_permission" VALUES (273, 'SC-SL-CF-001', 'View List', 'SC-SL-CF', 10);
INSERT INTO "public"."iy_m_permission" VALUES (229, 'SC-ZD-VMQ-002', 'View List', 'SC-ZD-VMQ', 20);
INSERT INTO "public"."iy_m_permission" VALUES (298, 'SC-S-I-R-001', 'View List', 'SC-S-I-R', 10);
INSERT INTO "public"."iy_m_permission" VALUES (478, 'SC-IM-SALE-RE-001', 'View List', 'SC-IM-SALE-RE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (225, 'SC-ZD-IMQ-002', 'View List', 'SC-ZD-IMQ', 20);
INSERT INTO "public"."iy_m_permission" VALUES (483, 'SC-INVENTORY-001', 'View List', 'SC-INVENTORY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (270, 'SC-RR-QUERY-004', 'View List', 'SC-RR-QUERY', 40);
INSERT INTO "public"."iy_m_permission" VALUES (283, 'SC-BD-001', 'View List', 'SC-BD', 10);
INSERT INTO "public"."iy_m_permission" VALUES (258, 'SC-CS-DETAIL-001', 'View List', 'SC-CS-DETAIL', 10);
INSERT INTO "public"."iy_m_permission" VALUES (315, 'SC-RV-003', 'View List', 'SC-RV', 30);
INSERT INTO "public"."iy_m_permission" VALUES (244, 'SC-CASHIER-007', 'View List', 'SC-CASHIER', 70);
INSERT INTO "public"."iy_m_permission" VALUES (431, 'SC-MATEL-ENTRY-007', 'View List', 'SC-MATEL-ENTRY', 70);
INSERT INTO "public"."iy_m_permission" VALUES (221, 'SC-OD-FAILED-001', 'View List', 'SC-OD-FAILED', 40);
INSERT INTO "public"."iy_m_permission" VALUES (233, 'SC-RF-GROUP-001', 'View List', 'SC-RF-GROUP', 10);
INSERT INTO "public"."iy_m_permission" VALUES (311, 'SC-PI-004', 'View List', 'SC-PI', 40);
INSERT INTO "public"."iy_m_permission" VALUES (440, 'SC-STORE-SALE-003', 'Export', 'SC-STORE-SALE', 30);
INSERT INTO "public"."iy_m_permission" VALUES (132, 'SC-V-RECEIPT-006', 'Export', 'SC-V-RECEIPT', 60);
INSERT INTO "public"."iy_m_permission" VALUES (127, 'SC-RECEIPT-006', 'Export', 'SC-RECEIPT', 60);
INSERT INTO "public"."iy_m_permission" VALUES (524, 'SC-ZD-SMQ-001', 'View', 'SC-ZD-SMQ', 10);
INSERT INTO "public"."iy_m_permission" VALUES (525, 'SC-ZD-SMQ-002', 'View List', 'SC-ZD-SMQ', 20);
INSERT INTO "public"."iy_m_permission" VALUES (526, 'SC-ZD-SMQ-003', 'Export', 'SC-ZD-SMQ', 30);
INSERT INTO "public"."iy_m_permission" VALUES (527, 'SC-ST-TRANSIN-001', 'Add', 'SC-ST-TRANSIN', 10);
INSERT INTO "public"."iy_m_permission" VALUES (528, 'SC-ST-TRANSIN-002', 'View', 'SC-ST-TRANSIN', 20);
INSERT INTO "public"."iy_m_permission" VALUES (529, 'SC-ST-TRANSIN-003', 'Modify', 'SC-ST-TRANSIN', 30);
INSERT INTO "public"."iy_m_permission" VALUES (530, 'SC-ST-TRANSIN-004', 'View List', 'SC-ST-TRANSIN', 40);
INSERT INTO "public"."iy_m_permission" VALUES (531, 'SC-ST-TRANSIN-005', 'Approval Records', 'SC-ST-TRANSIN', 50);
INSERT INTO "public"."iy_m_permission" VALUES (532, 'SC-ST-TRANSIN-006', 'Export', 'SC-ST-TRANSIN', 60);
INSERT INTO "public"."iy_m_permission" VALUES (322, 'SC-RW-005', 'Export', 'SC-RW', 50);
INSERT INTO "public"."iy_m_permission" VALUES (317, 'SC-RV-005', 'Export', 'SC-RV', 50);
INSERT INTO "public"."iy_m_permission" VALUES (245, 'SC-CASHIER-008', 'Delete', 'SC-CASHIER', 80);
INSERT INTO "public"."iy_m_permission" VALUES (533, 'SC-TRANSFER-MOD-001', 'Add', 'SC-TRANSFER-MOD', 10);
INSERT INTO "public"."iy_m_permission" VALUES (534, 'SC-TRANSFER-MOD-002', 'View', 'SC-TRANSFER-MOD', 20);
INSERT INTO "public"."iy_m_permission" VALUES (535, 'SC-TRANSFER-MOD-003', 'Modify', 'SC-TRANSFER-MOD', 30);
INSERT INTO "public"."iy_m_permission" VALUES (246, 'SC-CASHIER-009', 'Export', 'SC-CASHIER', 90);
INSERT INTO "public"."iy_m_permission" VALUES (539, 'SC-OL-001', 'View List', 'SC-OL', 10);
INSERT INTO "public"."iy_m_permission" VALUES (541, 'SC-JF-QUERY-006', 'Export', 'SC-JF-QUERY', 60);
INSERT INTO "public"."iy_m_permission" VALUES (542, 'SC-ORDER-DC-001', 'View', 'SC-ORDER-DC', 10);
INSERT INTO "public"."iy_m_permission" VALUES (329, 'SC-PRI-CHANGE-005', 'Export', 'SC-PRI-CHANGE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (501, 'SC-SUS-LIST-005', 'Export', 'SC-SUS-LIST', 20);
INSERT INTO "public"."iy_m_permission" VALUES (312, 'SC-PI-005', 'Export', 'SC-PI', 50);
INSERT INTO "public"."iy_m_permission" VALUES (510, 'SC-INVOICE-001', 'Add', 'SC-INVOICE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (509, 'SC-INVOICE-005', 'Export', 'SC-INVOICE', 50);
INSERT INTO "public"."iy_m_permission" VALUES (545, 'SC-DAY-OD-FAILED-002', 'Export', 'SC-DAY-FAILED', 20);
INSERT INTO "public"."iy_m_permission" VALUES (546, 'SC-DAY-OD-FAILED-003', 'View', 'SC-DAY-FAILED', 30);
INSERT INTO "public"."iy_m_permission" VALUES (540, 'SC-RR-MODIF-004', 'Export', 'SC-RR-MODIF', 40);
INSERT INTO "public"."iy_m_permission" VALUES (544, 'SC-DAY-OD-FAILED-001', 'View List', 'SC-DAY-FAILED', 10);
INSERT INTO "public"."iy_m_permission" VALUES (543, 'SC-ORDER-DC-002', 'Add', 'SC-ORDER-DC', 20);
INSERT INTO "public"."iy_m_permission" VALUES (547, 'SC-ORDER-DC-003', 'Edit', 'SC-ORDER-DC', 30);
INSERT INTO "public"."iy_m_permission" VALUES (548, 'SC-CORE-DAILY-001', 'Export', 'SC-CORE-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (549, 'SC-SERVE-DAILY-001', 'Export', 'SC-SERVE-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (550, 'SC-RECONCILE-001', 'Export', 'SC-RECONCILE', 10);
INSERT INTO "public"."iy_m_permission" VALUES (551, 'SC-BD-003', 'Export', 'SC-BD', 30);
INSERT INTO "public"."iy_m_permission" VALUES (552, 'SC-IT-TRANSFER-001', 'Add', 'SC-IT-TRANSFER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (553, 'SC-IT-TRANSFER-002', 'View', 'SC-IT-TRANSFER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (554, 'SC-IT-TRANSFER-003', 'Modify', 'SC-IT-TRANSFER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (555, 'SC-IT-TRANSFER-004', 'View List', 'SC-IT-TRANSFER', 40);
INSERT INTO "public"."iy_m_permission" VALUES (556, 'SC-IT-TRANSFER-005', 'Export', 'SC-IT-TRANSFER', 50);
INSERT INTO "public"."iy_m_permission" VALUES (557, 'SC-CS-DETAIL-002', 'Export', 'SC-CS-DETAIL', 20);
INSERT INTO "public"."iy_m_permission" VALUES (558, 'SC-IT-TR-DAILY-001', 'Print', 'SC-IT-TR-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (559, 'SC-IT-TR-DAILY-002', 'Export', 'SC-IT-TR-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (560, 'SC-IT-TRANSFER-006', 'Approval Records', 'SC-IT-TRANSFER', 60);
INSERT INTO "public"."iy_m_permission" VALUES (561, 'SC-JF-QUERY-007', 'Approval Records', 'SC-JF-QUERY', 70);
INSERT INTO "public"."iy_m_permission" VALUES (562, 'SC-RECEIPT-007', 'Approval Records', 'SC-RECEIPT', 70);
INSERT INTO "public"."iy_m_permission" VALUES (563, 'SC-V-RECEIPT-007', 'Approval Records', 'SC-V-RECEIPT', 70);
INSERT INTO "public"."iy_m_permission" VALUES (564, 'SC-RW-006', 'Approval Records', 'SC-RW', 60);
INSERT INTO "public"."iy_m_permission" VALUES (565, 'SC-RV-006', 'Approval Records', 'SC-RV', 60);
INSERT INTO "public"."iy_m_permission" VALUES (566, 'SC-RR-MODIF-005', 'Approval Records', 'SC-RR-MODIF', 50);
INSERT INTO "public"."iy_m_permission" VALUES (567, 'SC-PD-SETTING-008', 'Approval Records', 'SC-PD-SETTING', 80);
INSERT INTO "public"."iy_m_permission" VALUES (568, 'SC-S-I-R-004', 'Approval Records', 'SC-S-I-R', 40);
INSERT INTO "public"."iy_m_permission" VALUES (569, 'SC-PM-005', 'Approval Records', 'SC-PM', 50);
INSERT INTO "public"."iy_m_permission" VALUES (570, 'SC-PRICE-LABEL-001', 'View List', 'SC-PRICE-LABEL', 10);
INSERT INTO "public"."iy_m_permission" VALUES (571, 'SC-PRICE-LABEL-002', 'Print', 'SC-PRICE-LABEL', 20);
INSERT INTO "public"."iy_m_permission" VALUES (304, 'SC-CA-002', 'View List', 'SC-CA', 20);
INSERT INTO "public"."iy_m_permission" VALUES (572, 'SC-TRANSFER-MOD-004', 'View List', 'SC-TRANSFER-MOD', 40);
INSERT INTO "public"."iy_m_permission" VALUES (573, 'SC-IT-TR-DAILY-003', 'View List', 'SC-IT-TR-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (574, 'SC-SERVE-DAILY-002', 'View List', 'SC-SERVE-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (575, 'SC-CORE-DAILY-002', 'View List', 'SC-CORE-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (576, 'SC-ORDER-REPORT-001', 'View List', 'SC-ORDER-REPORT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (578, 'SC-RECONCILE-002', 'VIew List', 'SC-RECONCILE', 20);
INSERT INTO "public"."iy_m_permission" VALUES (579, 'SC-SHELF-MAINT-001', 'View List', 'SC-SHELF-MAINT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (580, 'SC-SHELF-MAINT-002', 'View', 'SC-SHELF-MAINT', 20);
INSERT INTO "public"."iy_m_permission" VALUES (581, 'SC-RETURN-DAILY-001', 'VIew List', 'SC-RETURN-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (582, 'SC-RETURN-DAILY-002', 'Print', 'SC-RETURN-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (583, 'SC-RETURN-DAILY-003', 'Export', 'SC-RETURN-DAILY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (584, 'SC-DC-RET-DAILY-001', 'VIew List', 'SC-DC-RET-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (585, 'SC-DC-RET-DAILY-002', 'Print', 'SC-DC-RET-DAILY', 20);
INSERT INTO "public"."iy_m_permission" VALUES (586, 'SC-DC-RET-DAILY-003', 'Export', 'SC-DC-RET-DAILY', 30);
INSERT INTO "public"."iy_m_permission" VALUES (602, 'SC-PD-NON-COUNT', 'VIew List', 'SC-PD-NON-COUNT', 10);
INSERT INTO "public"."iy_m_permission" VALUES (599, 'SC-SHOP-DIFFER-001', 'VIew List', 'SC-SHOP-DIFFER', 10);
INSERT INTO "public"."iy_m_permission" VALUES (600, 'SC-SHOP-DIFFER-002', 'Export', 'SC-SHOP-DIFFER', 20);
INSERT INTO "public"."iy_m_permission" VALUES (601, 'SC-SHOP-DIFFER-003', 'VIew', 'SC-SHOP-DIFFER', 30);
INSERT INTO "public"."iy_m_permission" VALUES (603, 'SC-DC-HHT-DAILY-001', 'View List', 'SC-DC-HHT-DAILY', 10);
INSERT INTO "public"."iy_m_permission" VALUES (604, 'SC-ST-CLEAR-001', 'View List', 'SC-ST-CLEAR', 10);
INSERT INTO "public"."iy_m_permission" VALUES (605, 'SC-ST-CLEAR-002', 'Add', 'SC-ST-CLEAR', 20);
INSERT INTO "public"."iy_m_permission" VALUES (606, 'SC-ST-CLEAR-003', 'Import', 'SC-ST-CLEAR', 30);
INSERT INTO "public"."iy_m_permission" VALUES (607, 'SC-OD-orderHHTR-001', 'View List', 'SC-OD-orderHHTR', 10);
INSERT INTO "public"."iy_m_permission" VALUES (608, 'SC-OD-orderHHTR-002', 'Export', 'SC-OD-orderHHTR', 20);
INSERT INTO "public"."iy_m_permission" VALUES (609, 'SC-RU', 'VIew List', 'SC-RU', 10);
INSERT INTO "public"."iy_m_permission" VALUES (610, 'SC-RU-VIEW', 'View', 'SC-RU', 20);
INSERT INTO "public"."iy_m_permission" VALUES (611, 'SC-RU-ADD', 'Add', 'SC-RU', 30);
INSERT INTO "public"."iy_m_permission" VALUES (612, 'SC-RU-EDIT', 'Edit', 'SC-RU', 40);
