package cn.com.bbut.iy.itemmaster.entity.sa0070;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@EqualsAndHashCode(callSuper = false)
@AllArgsConstructor
@NoArgsConstructor
public class SA0070 extends SA0070Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.acc_date
     *
     * @mbg.generated
     */
    private String accDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.store_cd
     *
     * @mbg.generated
     */
    private String storeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.article_id
     *
     * @mbg.generated
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.barcode
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.old_price
     *
     * @mbg.generated
     */
    private BigDecimal oldPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.new_price
     *
     * @mbg.generated
     */
    private BigDecimal newPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.delta_serial_no
     *
     * @mbg.generated
     */
    private Integer deltaSerialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa0070.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;
}