package cn.com.bbut.iy.itemmaster.dto.orderReport;

import cn.com.bbut.iy.itemmaster.dto.base.GridParamDTO;
import cn.com.bbut.iy.itemmaster.dto.base.role.ResourceViewDTO;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;

/**
 * @ClassName orderReportDto
 * @Description TODO
 * @Author Administrator
 * @Date 2020/7/31 16:09
 * @Version 1.0
 */
@Data
public class OrderReportParamDTO  extends GridParamDTO{
    private String dcName;
    private String articleId;

    private boolean flg = true;
   private String orderId;
    private String articleName;
    private String barcode;
    private String vendorId;
    private String promotionId;
    private String orderUnit;
    private String unitId;
    private String purchaseUnitId;
    private BigDecimal orderQty;
    private BigDecimal orderNochargeQty;
    private BigDecimal orderPrice;
    private BigDecimal orderAmt;
    private BigDecimal orderAmtNotax;
    private int limitStart;



    private BigDecimal orderTax;
    private BigDecimal receivePrice;
    private BigDecimal receiveQty;
    private BigDecimal receiveNoChargeQty;
    private BigDecimal receiveTotalQty;
    private BigDecimal receiveTotalAmt;
    private BigDecimal receiveTotalAmtNotax;
    private BigDecimal varianceQty;


 private BigDecimal receiveTax;
    private String uploadFlg;
    private String uploadDate;
    private String storeCd;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.create_ymd
     *
     * @mbg.generated
     */
    private String createYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.create_hms
     *
     * @mbg.generated
     */
    private String createHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.update_ymd
     *
     * @mbg.generated
     */
    private String updateYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.update_hms
     *
     * @mbg.generated
     */
    private String updateHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.update_screen_id
     *
     * @mbg.generated
     */
    private String updateScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.update_ip_address
     *
     * @mbg.generated
     */
    private String updateIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.nr_update_flg
     *
     * @mbg.generated
     */
    private String nrUpdateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.nr_ymd
     *
     * @mbg.generated
     */
    private String nrYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.nr_hms
     *
     * @mbg.generated
     */
    private String nrHms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.reason_id
     *
     * @mbg.generated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.adjust_amt
     *
     * @mbg.generated


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.adjust_qty
     *
     * @mbg.generated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.order_date
     *
     * @mbg.generated
     */
    private String orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.delivery_date
     *
     * @mbg.generated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.order_specifi
     *
     * @mbg.generated
     */
    private String orderSpecifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.lowest_order
     *
     * @mbg.generated
     */
    private String lowestOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.goods_quantity
     *
     * @mbg.generated
     */
    private String gQuantity;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od0010.receiving_differences
     *variance;
     * @mbg.generated
     */
    private String receivingDifferences;

    private BigDecimal qty1;
    private BigDecimal autoOrderQty;
    private BigDecimal variance;



    private String am;
    private String inventoryQty;
    private String psd;
    private  String storeName;
    private String city;
    private String ofc;
    private String depCd;
    private String pmaCd;
    private String categoryCd;
    private String subCategoryCd;
    private String pmaName;
    private List<ResourceViewDTO> resources;

    /** 大区CD */
    private String regionCd;
    /** 城市CD */
    private String cityCd;
    /** 区域CD */
    private String districtCd;
    /** 店铺CD */
    /** 权限包含的所有店铺编号 */
    private Collection<String> stores;


}
